### ISSUE TITLE
[Bug]: Cloudflare Pages -- Workers not being processed by miniflare

### ISSUE THREAD

**Issue by kevinelliott** [solidjs/solid-start#1000]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When using the solid-start-cloudflare-pages adapter, the functions in the functions path are not getting executed/found by miniflare when running with `pnpm dev`.

### Expected behavior 🤔

Functions should run!

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

**Comment by ryansolid** [comment]
In setting up for SolidStart's next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
