### ISSUE TITLE
[Bug?]: Type checking with @total-typescript/ts-reset fails

### ISSUE THREAD

**Issue by lirbank** [solidjs/solid-start#1008]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Type checking SolidStart with https://www.npmjs.com/package/@total-typescript/ts-reset fails.

### Expected behavior 🤔

Type check should pass.

### Steps to reproduce 🕹

Steps:

1. `npm init solid@latest`
2. `npm install`
3. `npm install @total-typescript/ts-reset`
4. Create a `reset.d.ts` file in your project with these contents (see https://www.npmjs.com/package/@total-typescript/ts-reset#user-content-get-started):

```ts
// Do not add any other lines of code to this file!
import "@total-typescript/ts-reset";
```
5. `npx tsc --noEmit`

### Context 🔦

The https://www.npmjs.com/package/@total-typescript/ts-reset package has some very useful better default types for some common functions. I use it in all my projects, it would be epic if it worked with SolidStart too.

**Comment by lirbank** [comment]
Related to https://github.com/solidjs/solid-start/issues/976

**Comment by lirbank** [comment]
In the meantime, here is a nice workaround:
https://github.com/solidjs/solid-start/issues/255#issuecomment-1307003993

**Comment by ryansolid** [comment]
In setting up for SolidStart's next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
