### ISSUE TITLE
[Bug?]: website right side content dont change after clicking different page on the left

### ISSUE THREAD

**Issue by xarthurx** [solidjs/solid-start#1009]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

![image](https://github.com/solidjs/solid-start/assets/1921878/ad691f61-34a8-4e4c-9363-049b193e81ba)

See img above, quite self-explanatory.

This issue will disappear (right side content will change) after refresh the website.

### Expected behavior 🤔

Right side content will change when clicking the left side page.

### Steps to reproduce 🕹

Not a library issue. pass.

### Context 🔦

Not a library issue. pass.

### Your environment 🌎

```shell
Browser: Chrome
```

**Comment by ryansolid** [comment]
In setting up for SolidStart's next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
