### ISSUE TITLE
[Bug?]: cannot use icon without the class="xxx" in "A" link

### ISSUE THREAD

**Issue by xarthurx** [solidjs/solid-start#1010]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

![image](https://github.com/solidjs/solid-start/assets/1921878/ee739999-507c-4403-9197-7e7d4b452d3c)

```html
      <a i-line-md-github-loop target="_blank" href="https://github.com/xarthurx"></a>
      <A i-line-md-github-loop target="_blank" href="https://github.com/xarthurx"></A>
      <A class="i-line-md-github-loop" target="_blank" href="https://github.com/xarthurx"></A>
```

When using unocss, putting icon class directly in solid-start's `A` will not display the icon.
The icon name has to be put into a `class=<icon-name>` format.

But with the normal `a` DOM, it is shown correctly.

### Expected behavior 🤔

`A` and `a` will behave the same and both show the icon correctly.

### Steps to reproduce 🕹

Steps:

1. Use `A` to create a link
2. put an css-like icon name as a class, without the `class=<icon>` syntax
3. render the page

**Comment by xarthurx** [comment]
Actually, I realize the `<A>` tag cannot take any css without the `class` prefix.

**Comment by ryansolid** [comment]
It's because it isn't a known boolean attribute we treat it like a standard attribute when passed through a component. I suppose the native behavior of it working like a boolean is unexpected but this is where things landed after a long debate around this. https://github.com/solidjs/solid/issues/1101

The weird part is I wonder if this bug got re-introduced again. I thought we resolved that we should always treat non-boolean attributes as `="true"`

**Comment by ryansolid** [comment]
In setting up for SolidStart's next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
