### ISSUE TITLE
[Bug?]: Global Suspense trigger reruns everything during SSR

### ISSUE THREAD

**Issue by emdede** [solidjs/solid-start#1030]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When the global suspense boundary is triggered during SSR everything beneath it gets rerun.
This includes pages and their routeData functions.

### Expected behavior 🤔

Resource completion should not cause everything to run twice. Instead, it should only have to run once and be memo'd as Suspense usually works and is expected to work.

### Steps to reproduce 🕹

https://stackblitz.com/edit/solid-ssr-vite-pcbdkr?file=src%2Froot.tsx

### Context 🔦

I fiddled around a bit and noticed that if you have a Suspense that is inside a Component that creates a resource this does not happen:
https://stackblitz.com/edit/solid-ssr-vite-6v74kf?file=src%2Froutes%2Findex.tsx

While this works for the stackblitz example. I tried to apply this to my own project that is much bigger than that but I couldn't achieve the same result.

I tried putting Suspense's left and right, whack-a-mole, but it would always call my main layout route twice.

Apart from this being a bug IMO, I feel a bit more clarity on how to "correctly" use Suspense would help in this matter, too. It's non-intuitive to have different Suspense behavior when it's put in different places. Note that when you move the Suspense boundary in the example mentioned above out of the component and into the route, it will be broken once again - seemingly at random.

**Comment by ryansolid** [comment]
A triggered Suspense boundary will re-run anything under it including data functions on the server but all resources should have a unique hydration id that allows them to be cached between renders so they don't refetch.

See: https://stackblitz.com/edit/solid-ssr-vite-zch3wg?file=src%2Froutes%2Findex.tsx

A nested Suspense boundary will mean that Suspense has this behavior up to the nearest boundary above the read. So in your second example it doesn't end up running the component up to there.

Admittedly this approach is much more similar on the server to what React does (I guess technically pre RSC as they do something different there), but given Solid's rendering speed (almost 10x React in SSR) this seemed like a reasonable trade off because reactivity on the server is significantly more expensive then jamming a few strings together. Where there is problematic would be any expensive user space calculations that would happen on re-render. So I'd say this is by design in the current model.

**Comment by emdede** [comment]
Thank you for your explanation, Ryan. It does make sense. Exactly this Reacty feel to it made me think this can't be intentional. ;D

With your explanation provided, I think it's safe to say that this is not an issue. However, this is among many minor hidden gotchas that should be documented a bit better with something like a Warning Hint, imo.
