### ISSUE TITLE
[Bug?]: Page contents listing doesn't change when moving between pages in the docs

### ISSUE THREAD

**Issue by tasgon** [solidjs/solid-start#1042]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When clicking between pages, the 'On this page' section doesn't update and only shows the content listing of the first page loaded.

### Expected behavior 🤔

The section should update to correspond to the new page.

### Steps to reproduce 🕹

Steps:

1. Open the [SolidStart docs](https://start.solidjs.com/getting-started/what-is-solidstart).
2. Click on a different page.

**Comment by edivados** [comment]
Opened a PR.

**Comment by ryansolid** [comment]
In setting up for SolidStart's next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
