### ISSUE TITLE
Add support for `Portal` in SSR

### ISSUE THREAD

**Issue by BierDav** [solidjs/solid-start#1043]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I want to use the `Portal` component in SSR, and I need it to be included in the SSR rendered html. Currently, this seems impossible to me, or is there something I am missing?

### Examples 🌈

```
<Portal>
This should be included in the SSR html, but it is not. It will be rendered after the page is hydrated.
</Portal>
```

### Motivation 🔦

I'm working on `@suid` and want to add SSR support. One feature of modal dialogs is `keepMounted` this requires the `Portal` component to also work on the server.

**Comment by BierDav** [comment]
Please lovely people on GitHub, can someone give me any information on this, I'm desperately waiting for this. SSR is a **requirement** for us.

**Comment by F4b4n** [comment]
Hey, I've seen your comment on Reddit, I'm a new fan of solidjs. I had an "optimised" bing chat open, hope it helps:

Hi, this is Bing. I'm sorry to hear that you are having trouble with Portal support on SSR. I did some web search and found some information that might help you.

According to the SolidJS guide², Portal is a special component that allows you to render a child component outside of the current DOM hierarchy. It is useful for creating modals, tooltips, popovers, etc. However, Portal does not work well with SSR, because it relies on the document object, which is not available on the server. Therefore, Portal only renders after hydration, which means that the initial HTML sent from the server does not contain the Portal content.

One possible workaround for this issue is to use a custom component that renders a placeholder div on the server and replaces it with a Portal on the client. For example:

```jsx
import { Portal } from "solid-js/web";
import { createEffect, createSignal } from "solid-js";

function SSRPortal(props) {
  // Create a signal to track if the component is mounted
  const [isMounted, setIsMounted] = createSignal(false);

  // Set the signal to true after the component is mounted
  createEffect(() => {
    setIsMounted(true);
  });

  // Render a placeholder div on the server and a Portal on the client
  return isMounted() ? (
    <Portal mount={document.body}>{props.children}</Portal>
  ) : (
    <div id="portal-placeholder"></div>
  );
}
```

Then you can use this component instead of Portal in your code. For example:

```jsx
import { SSRPortal } from "./SSRPortal";

function App() {
  return (
    <div>
      <h1>Hello, world!</h1>
      <SSRPortal>
        <div>This is rendered in the body</div>
      </SSRPortal>
    </div>
  );
}
```

This way, you can render a component directly into the body from anywhere in your code, and still have SSR support. However, this solution has some limitations and drawbacks:

- The placeholder div must have a unique id that matches the mount prop of the Portal.
- The Portal content will not be visible until the client-side script is loaded and executed.
- The Portal content will not be accessible by crawlers or screen readers that rely on the initial HTML.

I hope this helps you with your problem. If you have any other questions, please feel free to ask. 😊

Source: Conversation with Bing, 05/09/2023
(1) SolidJS. https://www.solidjs.com/guides/server.
(2) Portal support on SSR : r/solidjs - Reddit. https://www.reddit.com/r/solidjs/comments/16a3hcv/portal_support_on_ssr/.
(3) What is SolidStart?. https://start.solidjs.com/.
(4) undefined. https://github.com/solidjs/solid-start/issues/1043.

**Comment by NawfelBgh** [comment]
I would say, just don't use Portals and position your element with css while resetting all styles inherited from parent nodes.

```
#your-element {
    all: initial; /* Reset styles inherited from parent */
    position: fixed; ...
}
```

**Comment by BierDav** [comment]
Yeah both of yor solutions are neat workarounds, that don't really put the element to the root. But that's exactly what I need. So i assume that this is a missing feature of solid-start

**Comment by BierDav** [comment]
Ok, so I've digged through the code of solidjs and have found a few issues. We would have to address when we would like to implement this feature. First the only we to cleanly implement this is to do it similar to how we handle meta tags. The `StartServer` under the hood provides the tags in the `PageEvent` which is then passed to and managed by the official `[solidjs/solid-meta](https://github.com/solidjs/solid-meta)` library. And now when we call the `<Head/>` component in our `root.tsx`, we get kindly rendered all the tags from this context in our head tag.

Know we have kinda a solution for this problem, but there is one big difference: The tags in the PageEvent only have limited functionality, because only the tag name and its direct properties are stored in a object with the type `TagDescription`. What we need is an array of strings that already contain the be pre-rendered portals to be able to directly insert them next to the body using the already from `solid-start` provided `<Body/>` component. We need to directly render, because else where we don't have access to the local Context's.

This seemed to be an obvious thing to implement, and I thought why this has not already been done before. But I have fear that this won't turn out well after hydration. But I don't have tested it yet, so there is still a chance that it just works.

**Comment by BierDav** [comment]
> I would say, just don't use Portals and position your element with css while resetting all styles inherited from parent nodes.
> 
> ```
> #your-element {
>     all: initial; /* Reset styles inherited from parent */
>     position: fixed; ...
> }
> ```

For now, I will just use this approach as a workaround and hope that it doesn't break existing code.

**Comment by ryansolid** [comment]
In setting up for SolidStart's next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.

**Comment by BierDav** [comment]
Still an issue

**Comment by gabrielmfern** [comment]
@ryansolid Could you reopen this? I think it's actual problem to consider fixing.
If there's a way already you could comment it here. I'd be fine with some sort of workaround, but I wasn't able to implement something like @F4b4n mentioned [here](https://github.com/solidjs/solid-start/issues/1043#issuecomment-1705731030). Maybe something like the current `client-only` function as well?

**Comment by gabrielmfern** [comment]
@BierDav With what I was doing I found out that the Portal was not working properly because of me bundling in some solid-js dependencies. I also had a bad time using `tsup-preset-solid`, not sure why, I made a similar config to it and it worked much better.

**Comment by BierDav** [comment]
All those solutions where the element stays deeply nested in the dom is really bad for transitions, because when you want to make a opacity transition for example and you have a element with position sticky (eg. a header) in the same level or above you, you get this weird behaviour where the transition works on the surface of all other elements except the header. Only after the transition finished the header updates and your "overlay" would be visible.

**Comment by BierDav** [comment]
I'm sure that this is technically possible and in my opinion the golden discipline of all JavaScript frameworks is to support ssr in a performant manner. Solid JS is really close, but unfortunately a few little building bricks are in my opinion still missing.

**Comment by rawptrx** [comment]
Now i have the same problem, content in <Portal> will never be rendered in ssr html

**Comment by rawptrx** [comment]
@BierDav now, i can understand why the behavior of  Portal component. if you have some content don't be find and parse by search engine crawler, you should use Portal, such as modal, or popup tip. if you don't wanna do this, don't use Portal.

**Comment by BierDav** [comment]
That's not the whole story. Because you lose all of the benefits of ssr. You might have a complicated persistent modal dialog. For this use case you need Portal in ssr
