### ISSUE TITLE
[Feature?]: Configure output directory

### ISSUE THREAD

**Issue by iainmerrick** [solidjs/solid-start#1063]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Solid Start currently creates writes its output directly to the project directory — `.solid` for common intermediate outputs, then one or more final outputs depending on the adapter. For example, the CloudFlare Pages adapter uses `dist/public` and `functions`. I'd like to be able to put _all_ the output in a different location.

Vite has `build.outDir` in its config, but that already has the default value `"dist"` so it would clash with the existing use of `dist` in solid-start adapters.

I suggest a new optional config on solid-start itself. `outDir` probably isn't the best name as it would get confused with Vite's `build.outDir`. Maybe something like `solidOutDir`?

### Examples 🌈

`vite.config.js` for the CloudFlare example would look like this:
```
import { defineConfig } from "vite";
import solid from "solid-start/vite";
import cloudflare from "solid-start-cloudflare-pages";

export default defineConfig({
  plugins: [solid({
    solidOutDir: "out", // <--------
    adapter: cloudflare({})
  })],
});
```
The directory structure would then be:
```
vite.config.ts
public/
src/
out/
├── .solid/
├── dist/
└── functions/
```

### Motivation 🔦

- I'd like to keep the project root tidy and avoid polluting it with arbitrary output files.
- If all the output is contained in a single directory, it's easier to configure tools like Turbo that want to trace build dependencies (vs having to list `[".solid/**", "dist/**", "functions/**"]` etc in `turbo.json`)
- This would also allow out-of-tree builds which are often useful. For example, we could generate multiple outputs with different adapters from the same Solid Start project.

**Comment by iainmerrick** [comment]
I'm happy to work on this if it's deemed useful. I got it working via `build.outDir` in my own fork, then realised that clashed with existing usage so a different design would be needed.

**Comment by joshuarossi** [comment]
hmmm, I have something similar. I am trying to set up a gitlab CI/CD process and the public folder is the default for gitlab on where it hosts the gitlab page (github Pages)

I couldn't find where it was defined how that folder works, because I was going to try and rename it so that they don't conflict.

Totally agree it would be nice to expose these settings so we can define where the output goes and where the input comes from...

**Comment by ryansolid** [comment]
In setting up for SolidStart's next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
