### ISSUE TITLE
[Bug?]: Prod server shuts down right away while build passes.

### ISSUE THREAD

**Issue by JesseKoldewijn** [solidjs/solid-start#1064]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Currently, when building I just get a couple of warning but nothing that seems to major. But when running ```solid-start start``` the production server just shuts itself down right away.

### Expected behavior 🤔

Either an error on build if something went wrong or from the prod server itself.

### Steps to reproduce 🕹

I got my own project on a public repo, if useful for repro: https://github.com/JesseKoldewijn/SolidStyles/tree/solid-start-core

ps. I.m using pnpm myself but I've also tested with npm, yarn and bun with the same results.

Steps:

1. Install deps
2. Build project
3. Run prod server
4. See it silently exit out right away

### Context 🔦

Unable to run production build, would like to be able to deploy my project.

### Your environment 🌎

```shell
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
Binaries:
  Node: 20.7.0
  npm: 10.1.0
  Yarn: 1.22.19
  pnpm: 8.7.4
Packages:
  solid-start: 0.3.6
  solid-js: 1.7.12
  vite: 4.4.9
```

**Comment by ryansolid** [comment]
In setting up for SolidStart's next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
