### ISSUE TITLE
[Bug?]: CSR still builds server code

### ISSUE THREAD

**Issue by stickyburn** [solidjs/solid-start#1074]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

- Develop a CSR app
- Add client side library like supabase
- Build with `pnpm run build`
- SSR code is outputted, with errors due to client lib requiring node environment

### Expected behavior 🤔

Should generate client side code only.

### Steps to reproduce 🕹

Steps:

1. create new project, n for SSR and barebones template
2. add client lib
3. build prod bundle
4. SSR code is generated, with errors in build process

### Context 🔦

Wanted to use solid-start with CSR to build a MVP. Things worked amazingly till I added supabase and started getting deployment errors. Seems like it's generating code for SSR, because a replica setup on plain solid and router works as expected.

Might be related to #978 

### Your environment 🌎

```shell
Arch linux
Node v18.18.0
Pnpm 8.8.0
solid-start ^0.3.6
```

**Comment by ryansolid** [comment]
The new CSR isolation I believe should help with this. Keep in mind CSR does require a server to render index.html but we now don't import the app on the server.. only the entry server.

In setting up for SolidStart's next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
