### ISSUE TITLE
[Bug?]: Broken vite config in websocket template

### ISSUE THREAD

**Issue by ronanru** [solidjs/solid-start#1075]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I generated a project with websocket template and no ssr. In the generated `vite.config.ts` the ssr option is included twice.
```ts
export default defineConfig({
  plugins: [
    solid({
      ssr: false,
      ssr: true, // <--------------
      experimental: {
        websocket: true,
      },
      adapter: startCloudflareWorkers({
        durableObjectsPersist: true,
        kvPersist: false,
      }),
    }),
  ],
});
```

### Steps to reproduce 🕹

![image](https://github.com/solidjs/solid-start/assets/35634442/1889867f-566e-4fe0-8357-7a60c820fc0f)

**Comment by ryansolid** [comment]
In setting up for SolidStart's next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
