### ISSUE TITLE
[Bug]: ErrorBoundary and ServerError

### ISSUE THREAD

**Issue by artecoop** [solidjs/solid-start#1078]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Hi!
I've stumbled upon the very same error filled in #596, but I need to add another issue related to this.

Copying and pasting the example shown in the docs:
https://start.solidjs.com/api/HttpStatusCode#setting-a-404-status-code-for-the-unmatched-routes

and entering `https://localhost:3000/slytherin` in the browser, the result displayed is "Gryffindor", as if the house passed is correct.

So  i've added, to check the result:
```ts
...

export default function House() {
	const house = useRouteData<typeof routeData>();
	console.log(house()); // <------
...
```
And now the error is displayed, even if it ignores the errorboundary, but this is already reported in the attached bug. 

But worse: if I click `Clear errors and retry`, the error disappear, showing "Gryffindor" again. This is very confusing behavior.

### Your environment 🌎

```shell
macOs Sonoma 14.0 arm
node v18.18.0
pnpm 8.8.0
solid-start 0.3.6
```

**Comment by ryansolid** [comment]
In setting up for SolidStart's next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
