### ISSUE TITLE
[Bug?]: with-trpc is breaking - seroval issue

### ISSUE THREAD

**Issue by birkskyum** [solidjs/solid-start#1092]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When starting the example, with Node 18, this is the result:

```sh

GET http://localhost:3000/
GET http://localhost:3000/api/trpc/example.hello?batch=1&input=%7B%220%22%3A%22World%22%7D
An unhandled error occured: Error: Cannot serialize function without reference ID.
    at Re (file:///Users/admin/repos/solid-start/node_modules/.pnpm/seroval@0.11.6/node_modules/seroval/dist/esm/production/index.mjs:3:30635)
```

Also note, the example uses an archived [solid-trpc](https://github.com/OrJDev/solid-trpc) package.

### Expected behavior 🤔

that the server starts

### Steps to reproduce 🕹

Steps:

0. checkout latest main in solid-start
1. Use node 18
2. `pnpm i`
3. go to examples/with-trpc
4. run `pnpm run dev`

### Context 🔦

Might be related to other recent seroval issues:
- https://github.com/solidjs/solid/issues/1919

**Comment by sysmat** [comment]
- same here 
- deps

```json
"type": "module",
  "devDependencies": {
    "@types/node": "^20.8.10",
    "csstype": "3.1.2",
    "esbuild": "^0.19.5",
    "postcss": "^8.4.31",
    "rollup": "^4.2.0",
    "solid-start-node": "^0.3.9",
    "typescript": "^5.2.2",
    "vite": "^4.5.0"
  },
  "dependencies": {
    "@solidjs/meta": "^0.29.1",
    "@solidjs/router": "^0.8.3",
    "drizzle-orm": "^0.28.6",
    "mysql2": "^3.6.3",
    "solid-js": "^1.8.5",
    "solid-start": "^0.3.9"
  },
  "engines": {
    "node": ">=18"
  }
```

**Comment by sysmat** [comment]
any progress?

**Comment by sysmat** [comment]
this totally stopper

**Comment by birkskyum** [comment]
@OrJDev  - do you think this can be solved by updating to mediakit, or is there an issue with seroval still?

**Comment by ItsGPhillips** [comment]
This has killed progress on one of my apps, a this should be an urgent issue

**Comment by ryansolid** [comment]
I remade the TRPC example in the new Beta and didn't face this issue. In general though I stopped using Tanstack Query for the example and that might be where the issue lies. Something with how hydration/serialization is working.

In setting up for SolidStart's next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
