### ISSUE TITLE
Any thoughts of utilizing snowpack(vs vite)?

### ISSUE THREAD

**Issue by kostadinnm** [solidjs/solid-start#11]
Hello.
Maybe this is more of a discussion question, but I'd like to mention it. Though this may be used as a recommendation to enable discussions here. I might of went into the discord channels, but still don't have such an account.

So, have you thought of using one of the more-promising imho snowpack unbundling build tool for the improvement of the solid starter? As to how I understand the diffs between snowpack and others, it offers more modern approach to setting up dev environment and for the actual builds, it can be made utilize only simpler and efficient `esbuild` without relying on prev-gen rollup/webpack stuff. [Snowpack v3.0](https://www.snowpack.dev/posts/2021-01-13-snowpack-3-0).

I personally am eager to delve into making a flexible ground for developing mixedly(i.e. browser+server)- rendered apps with multipage support and find the solidjs project as a step forward in that direction. So I hope its tooling could be kept up-to-date with the good js-stuff that's out there.

Cheers,
Kostadin

**Comment by ryansolid** [comment]
I started this Journey with Snowpack 3 and moved off of it when Vite 2 came out. I did that before SvelteKit did. The reason was I was having a really hard time getting Snowpack to play nice. I opened some PRs etc but it really felt like maintaining 4 separate build configs to get it working nicely. Ultimately the switch to Vite 2 just made everything easier. Small things they did on features just worked. The single config for SSR, glob imports, etc..

I wouldn't consider Vite 2 or Snowpack 3 that different in terms of moderness. To be fair Rollup still produces the best bundles. It's treeshaking/dead code elimination is better than anything, and ESBuild doesn't really lend to custom AST transforms which are essential to Solid's compilation. Both Snowpack and VIte use ESBuild under the hood. I suppose I could use it for the final production builds after everything is transformed by Vite and it's likely in those cases it wouldn't be that much bigger than Rollup, but I was mostly weighing on familiarity and size. 

In any case I'd argue that Vite 2 and Snowpack 3 are roughly equivalent projects that both leverage ESBuild (although I have to bypass a lot of it for Solid) with subtle differences that made me ultimately go with Vite. There are a couple of issues but I'm pretty happy with Vite currently. So while there are Solid Snowpack starters and the Astro integration my intention is to stay with Vite as I have looked into the alternatives.

**Comment by kostadinnm** [comment]
What do you mean by
>there are Solid Snowpack starters and the Astro integration

**Comment by ryansolid** [comment]
Example Snowpack Starter (client only): https://github.com/amoutonbrady/snowpack-solid
The Snowpack team did work to get Solid to work with SSR for Astro (which I was blocked on previosly): https://github.com/snowpackjs/astro/pull/656

**Comment by kostadinnm** [comment]
Wow, it seems like the plugin has just been mereged. If astro develops unified way of using any component library, that would be beneficial for all, I guess.

Actually, I'd like to discuss another characteristic of solid with you. It reminds me of a suite of functional primitives, that are supposed to compose any program in any language - [sodium](https://github.com/SodiumFRP/sodium). It has an attempt of implementation in javascript as well, but has been hindered to provide the full "FRP" experience because of missing weakref in the language. Now that the weakrefs are a fact, I guess the whole thing might get traction, as the author managed to mathematically proof sodium's "denotational" semantics.
Now, back to solid. It seems to me, that you might have invented independently a clone or a subset of what should be in a fully implemented functional reactive library. The author of sodium developed it in a similar manner, but managed to formalize its "completeness" as well. If I was an inventor of such a library, I'd be tempted to find the similarities and whether/to what extend the primitives of both the libraries are derivable to/from each other.

**Comment by ryansolid** [comment]
I found this interesting: http://sodium.nz/t/fine-grain-reactivity/557

In general, I think the project is interesting. Another one is https://kairojs.org/.
I try to keep up to date on reactive libraries and approaches. Admittedly I'd say reactivity only makes us 10% of my work on Solid. So much goes into features/SSR/compiler. But I usually find some time every year to spend a month on it.

**Comment by kostadinnm** [comment]
I'm closing this, along with a final reminder to enable discussions. Is that actually disabled!? I think I asked for "discussions" for [hybridjs](https://github.com/hybridsjs/hybrids)(another great and simplistict component lib) and I cannot find it there.

**Comment by ryansolid** [comment]
Discussions are disabled by default. I will probably turn them on here at some point. Right now still working stuff out here.
