### ISSUE TITLE
[Bug?]: api event is not valid

### ISSUE THREAD

**Issue by ardauzan** [solidjs/solid-start#1120]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

when I hit an api route, the params and request objects are always empty

### Expected behavior 🤔

I should get the params and request 

### Steps to reproduce 🕹

Steps:

1. start a fresh project with bare option
2. define an api route in a file 
3. just hit the endpoint and try to access params or request of the api event
4.

**Comment by ardauzan** [comment]
It seems like the issue is related to my system somehow. Im on fedora 39 running node 20.9.0.

**Comment by ryansolid** [comment]
In setting up for SolidStart's next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
