### ISSUE TITLE
[Bug?]: start-cloudflare-pages build fails with Vite 5

### ISSUE THREAD

**Issue by asterikx** [solidjs/solid-start#1134]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Reposting https://github.com/solidjs/vite-plugin-solid/pull/127#issuecomment-1835859078

I'm getting errors from `vite:define` in `solid-start-cloudflare-pages@0.3.10` with Vite 5:

```
user@MBP my-project % pnpm build

> my-solid-app@0.1.0 build /Users/user/my-project
> solid-start build

 solid-start build 
 version  0.3.10
(node:93293) ExperimentalWarning: The Ed25519 Web Crypto API algorithm is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
 adapter  cloudflare-pages

solid-start building client...
vite v5.0.4 building for production...
✓ 4 modules transformed.
[vite:define] Transform failed with 1 error:
error: Invalid define value (must be an entity name or valid JSON syntax): (() => {})
file: /Users/user/my-project/node_modules/.pnpm/solid-start@0.3.10_@solidjs+meta@0.29.1_@solidjs+router@0.9.1_solid-js@1.8.6_solid-start-clou_ykgf2egikbvfaqjxxzhhreqmsa/node_modules/solid-start/entry-client/mount.tsx
🐼 error [❌] Transform failed with 1 error:
error: Invalid define value (must be an entity name or valid JSON syntax): (() => {})
```

### Expected behavior 🤔

Successful build.

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

**Comment by ryansolid** [comment]
In setting up for SolidStart's next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.

**Comment by chin2km** [comment]
@ryansolid this might not be related, but I couldn't find any updated documentation for setting up deployments of a solid app to Cloudflare Pages.

There is one documentation at https://docs.solidjs.com/guides/how-to-guides/deployment/deploying-to-cloudflare
And one here: https://start.solidjs.com/api/vite#configuring-your-application
There is one on Cloudflare Pages itself: https://developers.cloudflare.com/pages/framework-guides/deploy-a-solid-site/#solidstart-cloudflare-configuration

I have this in my `vite.config.ts`

```tsx
import { defineConfig } from '@solidjs/start/config';

export default defineConfig({
  start: {
    server: {
      preset: 'cloudflare_module',
      rollupConfig: {
        external: ['__STATIC_CONTENT_MANIFEST', 'node:async_hooks'],
      },
    },
  },
});
```

and in the Cloudflare pages Build configurations, the "Build output directory" is configured to  `/.output` since this is the folder I see when building the project locally.
There is also a `.vinxi/build` folder generated. Tried setting the "Build output directory" to either of that but to no avail.
Could you please point what's wrong in the configuration or point me to the docs.

<img width="952" alt="Screenshot 2024-01-02 at 17 58 00" src="https://github.com/solidjs/solid-start/assets/10056971/92d5f368-7a54-42fc-b13a-5595939b5643">
