### ISSUE TITLE
[Bug?]: Update @rollup/plugin-commonjs to fix shebangs

### ISSUE THREAD

**Issue by JesseVelden** [solidjs/solid-start#1136]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When I try to build, I get the following error from Rollup, trying to build an external dependency which has a shebang at the top of the file:
```
Error [RollupError]: Unexpected character '!'
...
frame: '1: #!/usr/bin/env node\n' ,
pluginCode: 'PARSE_ERROR',
plugin: 'commonjs--resolver',
...
```

### Expected behavior 🤔

To build successfully

### Context 🔦

It seems to be recently fixed in Rollup: https://github.com/rollup/plugins/pull/1610.
Can we update to the latest `@rollup/plugin-common-js` version?

Also related to update Vite/ Rollup: https://github.com/solidjs/solid-start/issues/1123

**Comment by ryansolid** [comment]
plugin-common-js was causing really weird build issues which is why it is on an old version. That being said this all has been replaced in the next beta.

In setting up for SolidStart's next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
