### ISSUE TITLE
[Feature?]: Allow to dynamic environment variables in dist mode

### ISSUE THREAD

**Issue by BierDav** [solidjs/solid-start#1141]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Currently when you use environment variables with `solid-start build` all variables get instantly inlined, which is a bit annoying when you try to use the build result as a docker image, for example where I might want to override some variables

### Examples 🌈

We store the client id for the API as an environment variable, and we would like to be able to configure it in the docker-compose file

**Comment by ryansolid** [comment]
In setting up for SolidStart's next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
