### ISSUE TITLE
[Bug?]: Error running on Cloudflare Workers

### ISSUE THREAD

**Issue by JAD3N** [solidjs/solid-start#1160]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I receive the following error:
```
Cannot read properties of undefined (reading 'assets')
```

### Expected behavior 🤔

I was hoping it would load the route.

### Steps to reproduce 🕹

Steps:

1. Set up Wrangler following Nitro: https://nitro.unjs.io/deploy/providers/cloudflare#cloudflare-workers
2. Build using `NITRO_PRESET=cloudflare bun run build`
3. Run `bunx wrangler dev --local`
4. Open the browser and navigate to the website.

### Context 🔦

Just trying to get Solid Start (0.4.1) to work with Cloudflare Workers.

**Comment by ryansolid** [comment]
To use AsyncLocalStorage we need to use node compat in Cloudflare. Moreover because Nitro patches it by default and it breaks, we need to exempt it. I've had success by using the `cloudflare_module` preset and some settings. I actually documented this because this was the one adapter I had issues with.

We need to organize the docs better.. but check out the special not on this page: https://start.solidjs.com/api/vite

**Comment by JAD3N** [comment]
Just applied the referenced tweaks and everything appears to be working great. Thanks for pointing that out for me!
