### ISSUE TITLE
[Bug?]: /_server request gets stuck with async code inside middleware

### ISSUE THREAD

**Issue by JesseVelden** [solidjs/solid-start#1165]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

With the new @solid/start, the `/_server` request gets stuck and shows (pending) as status in Chrome's Network Inspector when using async code inside the middleware. When not using async code, it works fine.

### Expected behavior 🤔

The request resolves

### Steps to reproduce 🕹

Steps: 

1. Go to  https://codesandbox.io/p/devbox/solid-start-middleware-for-server-with-promise-session-not-working-6kz3tm?file=%2Fsrc%2Fmiddleware.ts%3A31%2C57
2. Run the dev server
3. Click on Generate New button in the preview window, and see the that the code actually executes the console.log but the request hangs as can be seen Network Inspector
4. If you uncomment the async code inside the `middleware.ts`, you can see it does work as expected

### Context 🔦

Middleware is needed for checking if a user is logged in. It is uses async functions to do that

### Your environment 🌎

```
Node.js v20.9.0

    "@solidjs/router": "^0.10.5",
    "@solidjs/start": "^0.4.1",
    "solid-js": "^1.8.7",
    "vinxi": "0.0.54"
```

**Comment by nksaraf** [comment]
Yup very peculiar. Will have to debug this carefully.

**Comment by edivados** [comment]
@nksaraf I think the issue is this.

The middleware in front of the server function creats a `FetchEvent` which calls [`toWebRequest`](https://github.com/unjs/h3/blob/53703dc860f1ff6fe7ce71d543deff1cfa810b11/src/utils/body.ts#L252C22-L252C22) creating a ReadableStream from the request body.

https://github.com/solidjs/solid-start/blob/a9b4b0532f76ce9f0c20545b4f6732a126771a7f/packages/start/server/middleware.ts#L59-L62

If I understand it correctly the unreleated await gives node a chance to read chunks and later we get stuck trying to read a request body that has already been read.

https://github.com/solidjs/solid-start/blob/a9b4b0532f76ce9f0c20545b4f6732a126771a7f/packages/start/config/server-handler.js#L102-L103

I verified this by replacing `toWebRequest` with a Proxy and not reading the body.

https://github.com/solidjs/solid-start/blob/a9b4b0532f76ce9f0c20545b4f6732a126771a7f/packages/start/server/middleware.ts#L20-L25

**Comment by nksaraf** [comment]
Ohh I think I faced something similar here: https://github.com/unjs/h3/issues/570

Okay I think we should do the proxy approach anyway so that nothing is called lazily.

**Comment by edivados** [comment]
ah interessting... guess you already ran into that.

We would proxy the WebRequest right, so something like this?

```js
function toWebRequestProxy(event) {
  let stream;
  const isWeb = !!event.web?.request;
  return new Proxy(new Request(
    event.web?.request ||
    new Request(getRequestURL(event), {
      // @ts-ignore Undici option
      duplex: "half",
      method: event.method,
      headers: event.headers
    })
  ), {
    get(target, prop) {
      if (prop === "body" && !isWeb) {
        return stream || (stream = getRequestWebStream(event))
      }
      return target[prop];
    }
  });
}
```

**Comment by edivados** [comment]
ah interessting... you already ran into that. 

So we would proxy the WebRequest and make sure the body is not read eagerly right?
For testing I just left `url` in tact because something was relying on it.

*I removed my prev suggestion because it was nonsense.*

**Comment by nksaraf** [comment]
I wonder if we should push this upwards to vinxi's server utils as well

**Comment by nksaraf** [comment]
Pulling this upstream into vinxi: https://github.com/nksaraf/vinxi/pull/101
