### ISSUE TITLE
[Bug?]:TypeError: Cannot read properties of null (reading 'length')

### ISSUE THREAD

**Issue by sysmat** [solidjs/solid-start#1250]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:
```
pnpm create solid@latest
pnpm install
pnpm dev

```
1. selecting tomvs
2. selectiing typescript

### Context 🔦

```
"scripts": {
    "dev": "vinxi dev",
    "build": "vinxi build",
    "start": "vinxi start"
  },
  "dependencies": {
    "@solidjs/router": "^0.10.9",
    "@solidjs/start": "^0.4.9",
    "solid-js": "^1.8.11",
    "unstorage": "1.10.1",
    "vinxi": "^0.1.2"
  },
  "engines": {
    "node": ">=18"
  }
```

### Your environment 🌎

```shell
- node v18.19.0
- pnpm 8.14.1
```

**Comment by lxsmnsyc** [comment]
we need more information

**Comment by sysmat** [comment]
To do mvc starter

**Comment by jzohdi** [comment]
@lxsmnsyc I just looked into this a bit more. During startup of the "todomvc" example project, I experienced the error that is the title of this reported issue.

**Comment by jzohdi** [comment]
@lxsmnsyc  I just looked into this a bit more. During startup of the "todomvc" example project, I experienced the error that is the title of this reported issue.  See screen shot below.

![image](https://github.com/solidjs/solid-start/assets/31998568/e7e373ee-09f8-4c21-80c2-c759c1eca201)

I could manage to get the app to work by changing the line in `src/lib/api.ts` from :
```ts
export async function getTodosFn() {
  return ((await storage.getItem("todos:data")) ?? []) as Todo[];
}
```
This function is used in the function `createAsync` in `index.tsx` 
```tsx
export default function TodoApp(props: RouteSectionProps) {
  const todos = createAsync(getTodos, { initialValue: [], deferStream: true });
  ...
  ...
}
```
The question I have now is whether it is expected behavior or should the initial value be returned instead of null? null being returned by storage.getItem("todos:data")

**Comment by ryansolid** [comment]
`initialValue` is what we have before createAsync resolves. If createAsync finds `null` then `null is the value. So this is correct. The problem here is reading from unstorage. In the repo I have the `[]`. I am gathering these files are missing when you do a local install. This is a CLI bug I take it but we aren't going to be fixing this version of the CLI and will be replacing it shortly. I will update the example to have default values from the API.
