### ISSUE TITLE
[Bug?]: onBeforeResponse response object is empty in middleware

### ISSUE THREAD

**Issue by Numnumberry** [solidjs/solid-start#1278]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The response object is not properly populated according to the Response TypeScript definition. There is only a "body" property. I am attempting to write headers.
```typescript
import { createMiddleware } from '@solidjs/start/server'

export default createMiddleware({
  onBeforeResponse(event, response) {
    console.log(response)
    response.headers.set('test', 'test')
  }
})
```
```
{
  body: ReadableStream { locked: false, state: 'readable', supportsBYOB: false }
}
[nitro] [request error] [unhandled] Cannot read properties of undefined (reading 'set')
  at onBeforeResponse (./.output/server/chunks/nitro/node-server.mjs:7610:29)  
  at ./.output/server/chunks/nitro/node-server.mjs:7599:31  
  at _callHandler (./.output/server/chunks/nitro/node-server.mjs:2281:13)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async Object.handler (./.output/server/chunks/nitro/node-server.mjs:2390:19)  
  at async Server.toNodeHandle (./.output/server/chunks/nitro/node-server.mjs:2579:7)
```

### Expected behavior 🤔

The response object, if provided inside onBeforeResponse, should be populated and usable.

### Steps to reproduce 🕹

Steps:

1. Init a solid start bare project
2. create a middleware that uses onBeforeResponse and the response parameter

### Context 🔦

I am trying to find a way to write response headers for the user, as well as access response headers for logging.

### Your environment 🌎

```shell
"dependencies": {
    "@solidjs/start": "^0.4.10",
    "solid-js": "^1.8.11",
    "vinxi": "^0.1.4"
  }
```

**Comment by ryansolid** [comment]
My understanding is this by design of Nitro hooks. The body is whatever was returned. I'm thinking we should probably just wrap this differently and not use their conventions as it is odd. 

Generally use `setHeader` rather than try to manipulate the response directly I think might be the coarse of action. This does deserve more discussion though.

**Comment by Numnumberry** [comment]
> The body is whatever was returned.

Yeah after some further digging this does seem to be the behavior. I agree its odd. Coming from other API's I am used to set the headers on the response, I should have realized there was a solid-start provided API to do that. Which now makes me think of what is the purpose of the provided Nitro response. I guess it is useful if someone really needs to dig into something. But if its kept, then yeah should at least have some more accurate typings.

**Comment by ryansolid** [comment]
It seems the design was intentional so people could swap the response, but we could just change the API here to suit our needs I think. I'm open to discussion on that. The reason I want the response there is so I can look at it mostly. I suppose if what I got was an Error I might want to send back a different response. I should see how it cascades through. Part of this comes from better understanding the current behavior too.

**Comment by ryansolid** [comment]
So I'm going to fix the types for this issue. What it should be doing is a more open discussion.
