### ISSUE TITLE
[Bug?]: <HttpStatusCode> doesn't work in mode:async

### ISSUE THREAD

**Issue by indeyets** [solidjs/solid-start#1410]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Whenever solid-start's server rendering is in async-mode, `<HttpStatusCode` does nothing

### Expected behavior 🤔

it should be possible to change status of responses using `<HttpStatusCode>` in async mode

### Steps to reproduce 🕹

Steps:

1. checkout https://github.com/indeyets/solid-start-error and install dependencies
2. run `npm run dev`
3. notice that status is supposed to be be 404: https://github.com/indeyets/solid-start-error/blob/main/src/app.tsx#L23
4. run `curl --HEAD -v 'http://localhost:3000/'` (or use browser's developer tools) and see that it still returns `200 OK`

**Comment by ryansolid** [comment]
Thanks for reporting. I think we hit this before but forgot to track it. This is likely a Solid core bug but will investigate.

**Comment by ryansolid** [comment]
Yeah this is an interesting one. Because I thought the issue was in Solid but it is more that while I can delay cleanup there we still have a problem because we are basing our undo on whether the response has been handled and really it depends on whether its been handled or conceptually we are done rendering. It's possible that we haven't returned the response and it is done rendering in which case we should skip it like this and there are cases where we have responded on the stream and shouldn't clear it even though we aren't done rendering.

Ideally we'd have a generic way to handle this, but for now I think start should mark when it thinks it is done rendering and we check either condition.
