### ISSUE TITLE
Redirect doesn't early exit component when loading from browser address bar

### ISSUE THREAD

**Issue by aquaductape** [solidjs/solid-start#1457]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When redirecting inside async server function call, the rest of the component still continue to run inside the server. 

`routes/admin.tsx`
```tsx
import { cache, createAsync, redirect } from "@solidjs/router";

const isAuthorized = false;

const getUser = cache(async () => {
  "use server";

  console.log("getUser: before redirect"); // logs
  if (!isAuthorized) {
    throw redirect("/about");
  }
  console.log("getUser: after redirect"); // doesn't log
  return {
    name: "John",
    age: 42,
  };
}, "getUser");

const Admin = () => {
  const res = createAsync(() => getUser());

  // server does unnecessary work here when redirecting
  console.log("Admin component"); // logs even after redirect, logs twice as well

  return (
    <div>
      <h1>admin</h1>
      <p>{res()?.name}</p>
    </div>
  );
};
```
Logs in server:
```
getUser: before redirect
Admin component
Admin component
```

### Expected behavior 🤔

Basically for redirecting to exit early in the component execution, like how NextJS 14 works.

NextJS 14
`app/admin/page.tsx`
```tsx
import { redirect } from 'next/navigation';

const isAuthorized = false;

const getUser = async () => {
  'use server';

  console.log('getUser: before redirect'); // logs
  if (!isAuthorized) {
    redirect('/about');
  }
  console.log('getUser: after redirect'); // doesn't log
  return {
    name: 'John',
    age: 42,
  };
};

const Admin = async () => {
  const res = await getUser();

  // server skips rest when redirecting
  console.log('Admin component'); // doesn't log

  return (
    <div>
      <h1>admin</h1>
      <p>{res?.name}</p>
    </div>
  );
};
```
Logs in server:
```
getUser: before redirect
```

### Steps to reproduce 🕹

Steps:

1. clone https://github.com/aquaductape/solid-start-redirect-test
2. enter `http://localhost:3000/admin` in browser address bar
3. redirects to `/about`
4. see terminal logs

### Your environment 🌎

```shell
System:
  OS: macOS 14.4.1 (23E224)
  Chip: Apple M1 Pro
Binaries:
  Node: v18.17.1
  npm: 10.1.0
npmPackages:
  solid-start: ^1.0.0-rc.0
```

**Comment by aquaductape** [comment]
Note, when navigating to admin page via clicking Admin anchor tag, 
<img width="342" alt="Screenshot 2024-04-22 at 10 32 11 PM" src="https://github.com/solidjs/solid-start/assets/29286430/d8102b5c-2126-4f5c-abd4-8c8a932e83b0">

it works to my expectation, early exits component after redirect like NextJS

**Comment by ryansolid** [comment]
This is by design to a certain degree. Our Async isn't blocking until where you read from the resource, not where you declare it. This avoids waterfalls that Next cannot. Similarly our resources don't throw and can be undefined. Again to be non-blocking. We are exploring space of doing blocking along the reactive graph rather than the components. But the short of this is Solid does not work like React and we need to work on our documentation.

**Comment by apatrida** [comment]
You can avoid the rendering part by not showing the component until the resource is ready.

Add `Show` as below

```
const Admin = async () => {
  const res = await getUser();

  createEffect(()=>{
       if (res()) {
           // won't log as by the time the component loads and redirects this won't get here
           console.log('Client - Admin component'); 
       }
  });
  
  // will log, as the resource hasn't loaded to do the redirect yet
  console.log('Client and Server - Admin component'); 

  return (
    <Show when{res()}>   
	    <div>
	      <h1>admin</h1>
	      <p>{res?.name}</p>
	    </div>
	</Show>
  );
};
```

**Comment by ryansolid** [comment]
Yeah this by design... reviewing this again I see that the log does happen, just in the browser, on navigation. The reason for the 3 logs is the way SSR works, it fetches (first log), renders the component (second log) and realizes it needs to suspend. Then on completion it renders the component again (realizes it needs to redirect).

In the client it fetches and renders the component (logging the render) then the server receives the response and logs the fetching, and then it resolves without re-running the component as reactivity just continues where it left off.
