### ISSUE TITLE
Streaming for deno adapter

### ISSUE THREAD

**Issue by nksaraf** [solidjs/solid-start#152]
As per this comment: https://twitter.com/lcasdev/status/1516838233359122434?s=20&t=ufhOOm_SiqHszQPWK0wmHQ, we should be able to stream the static assets from the Deno adapter

```ts
      const file = await Deno.open(`.${pathname}`);
      // Respond to the request with the style.css file.
      return new Response(file.readable, {
```

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
