### ISSUE TITLE
Pre-loading of JS assets. for faster navigation.

### ISSUE THREAD

**Issue by nksaraf** [solidjs/solid-start#153]

**Comment by nksaraf** [comment]
@ryansolid @rturnq Don't know if this is urgent for beta, but we should look into this. Probably requires cooperation between the router and the route manifest

**Comment by ryansolid** [comment]
What sort of preloading. You mean background preloading of everything? Or the links preloading on hover? or something else?

I don't feel this is urgent for beta regardless. We have an idea for router preloading on a dev branch of the router.

**Comment by nksaraf** [comment]
Links preloading on hover/visible mainly.. but yeah whatever can communicate preloading intent to us.. I agree not urgent for beta..

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
