### ISSUE TITLE
Post CSS support in order to support TailwindCSS

### ISSUE THREAD

**Issue by nksaraf** [solidjs/solid-start#155]
Works using vite

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
