### ISSUE TITLE
[Bug?]: Cannot get response returned by a server function via a GET request

### ISSUE THREAD

**Issue by Tommypop2** [solidjs/solid-start#1550]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Making a GET request to the correct endpoint with `serverFunction.url`, as well as the `args` query param results in an error:
```
{
  "statusCode": 500,
  "stack": []
}
```

### Expected behavior 🤔

The response from the server function should be sent verbatim to the client.

### Steps to reproduce 🕹

Steps:

1. Load https://stackblitz.com/edit/github-5jq8hh?file=src%2Froutes%2Findex.tsx
2. Observe the logged server error

### Context 🔦

I have attempted to fix this myself by patching Start:
I rewrote this
![image](https://github.com/solidjs/solid-start/assets/71586988/7fe15dd1-7811-42a4-a02e-e40abede273f)
To this
![image](https://github.com/solidjs/solid-start/assets/71586988/f57703c8-d8df-4dd9-9fbd-75e3c25e9f86)

This fixes the issue, but overwrites behaviour that I honestly don't fully understand.

**Comment by ryansolid** [comment]
There is a really awkward problem here and it is that somewhere lower in the stack.. trailing `/` versus not has different behavior most notable though is that we need to omit the trailing slash in POST, and include them in GET. The standard server function assumes the URL is for POST endpoint and returns without the trailing slash. So you need to grab the URL off the GET.. Either by using our wrapper function for TS (the public API).. `GET(serverFunction).url` with `GET` imported from `"@solidjs/start"` or by using the internal `serverFunction.GET.url`. I believe with this you don't need send args unless you intend to.

Anyway in the course of setting the raw response I found issues with GET being wrapped by HMR proxy which stopped URL from coming through. So yeah it won't work until the next release because of a number of bugs but I think I got this figured out now.
