### ISSUE TITLE
Fix HMR issues with routeData and server functions

### ISSUE THREAD

**Issue by nksaraf** [solidjs/solid-start#158]
There are a bunch of HMR related issues with `routeData` and `server` functions that need special consideration. @ghalle has been working on some fixes but this probably requires additional thought about how to approach this.

These PRs are contributing towards this:
- [ ] #149

**Comment by benbender** [comment]
I'm seeing '"request" is not available on the client. Use it within an `if (isServer)`'-errors while playing with the `with-auth`-example when not server-rendering. Is this known/expected? As this error-description is a bit vague, I'm unsure if this needs an issue or would be a duplicate.

**Comment by nksaraf** [comment]
This is a weird issue with vite codesplitting..should be fixed by https://github.com/solidjs/solid-start/commit/aae4836fbebba7315de3a2a8bc4321bad8829e29

**Comment by benbender** [comment]
Can confirm! Fixed for me in `0.1.0-alpha.92`. Thank you!

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
