### ISSUE TITLE
Possible to use both async and streaming SSR within the same page?

### ISSUE THREAD

**Issue by zejji** [solidjs/solid-start#16]
Is it possible to use both async and streaming SSR within the same page?

Consider the situation where:
- 3 requests to the backend API are required in order to fully populate a page;
- we know that 2 of those requests will return within ~5ms because they are being returned directly from a cache; and
- the remaining request takes > 500ms because it runs an uncached complex database query.

Ideally in this situation we could use async SSR for the first 2 requests (i.e. SolidJS should only start returning a response once those 2 backend requests have completed) and streaming SSR for the third, in order to avoid unnecessary page reflows and distracting visual flicker.

Is it possible to do this at present? As I understand it, Solid's SSR depends on Suspense boundaries to identify which content should be rendered asynchronously, so it presumably wouldn't currently be possible to distinguish between the two types of SSR (and therefore use them within the same page), but I would be very grateful for confirmation.

If not, is it something worth considering? This would also mean that users would not need to make a binary choice between async and streaming SSR.

**Comment by ryansolid** [comment]
Right now no. It depends on global config for hydration injected on the page. This will get reviewed when looking at new streaming improvements but right now no.

**Comment by zejji** [comment]
@ryansolid - many thanks for your reply.

Just a thought, but one option might be to have an attribute on the Suspense element which specifies whether it should be blocking for SSR purposes (i.e. async or streaming), with the ability to configure a default value in global config.

**Comment by ryansolid** [comment]
> Just a thought, but one option might be to have an attribute on the Suspense element which specifies whether it should be blocking for SSR purposes (i.e. async or streaming), with the ability to configure a default value in global config.

More or less. Not sure of the modes but once I get HTML streaming in the picture Suspense will need awareness of its state at the time of rendering from the server. So using that mechanism to make decisions per Suspense boundaries seems completely reasonable.

**Comment by ryansolid** [comment]
After implementing better streaming my opinion has changed some. I think this belongs more at the resource level. Async is simply streaming that doesn't flush until the end. When to send the initial payload is the question and I think the best way to do that is identify what requests need to be fulfilled before any HTML is sent. Per Suspense boundary makes less sense because we can only make this call once. Nesting gets ambiguous at that point.

To solve this a bit I'm exposing the renderTo____ APIs in an new entry and people will be able to control this exactly how they wish. That being said the resource based blocking I haven't implemented but that's more of a Solid Core thing and goes beyond this project specifically.
