### ISSUE TITLE
[Bug?]: Single-flight mutations don't include cookies

### ISSUE THREAD

**Issue by AlexErrant** [solidjs/solid-start#1637]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Consider a scenario where the username is stored in a cookie and rendered on the page if it's present. Currently, the username is not shown after a single flight mutation.

### Steps to reproduce 🕹

Steps:

1. Clone/apply [this commit](https://github.com/AlexErrant/solid-start/commit/edc65754fa4364d76a80cfa53d774e2352b02554) to examples/todomvc
2. Observe that the code adds middleware which adds a cookie to be displayed on todomvc.
3. Here's a video showing how adding something to the todo list (thus triggering a SFM) doesn't have the page show the cookie.

https://github.com/user-attachments/assets/0d938186-1c71-458a-9cb4-b642946f4b52

### Context 🔦

Note that [this commit](https://github.com/AlexErrant/solid-start/commit/043d7708ca9e11778a88f165138d610587a77ba2#diff-6917af85cf9bc6dbd1a81f06e2e29dbba0a01cc8deae5f088d7254eb97bfb7c6L286-R287) fixes the issue, but I'm not nearly confident enough in it to PR it. [It also doubles up the cookies for some reason.](https://github.com/user-attachments/assets/e62c7401-11c3-4a9b-8d3a-a271e1fd9754) Guidance/feedback welcome 😊

**Comment by ryansolid** [comment]
Hmm.. yeah the fix isn't quite right. The idea here is that revalidate is an explicit array or it is true to turn on the mode. What your code does is makes it always true unless those conditions aren't met at which point it revalidates nothing. 

I think I might see the issue. I think it is because we clone the event and put a new Request on it reflecting the newly navigated route. This request is missing all the headers so that might be the issue since you are trying to read the cookies in the cache function. I don't know that I want to put all headers across but cookies seem reasonable here. Let's give this fix a try.
