### ISSUE TITLE
Experimental or beta? README and official website conflicting

### ISSUE THREAD

**Issue by BoilingSoup** [solidjs/solid-start#177]
I followed the link in this repo's About section:
https://docs.solidjs.com/start/getting-started/what-is-solidstart

![image](https://user-images.githubusercontent.com/84747244/177206769-c72e1bb2-0d7c-439e-9afe-5918ce8b0880.png)

![image](https://user-images.githubusercontent.com/84747244/177206810-dbb2e997-7a1a-40de-a2aa-69fd19692305.png)

The info conflicts with each other so hope to see it clarified.
Cheers :)

**Comment by davedbase** [comment]
Hi there, note that the Docs URL you visited is actually not our official documentation release. The language here is geared towards a future release. There's conflicting messaging because we're in the process of working on everything. I'll close out the issue for now, but thanks for bringing this to our attention. I've asked the docs team to post a msg on the platform identifying they are alpha docs.
