### ISSUE TITLE
Setup historie with solid-start

### ISSUE THREAD

**Issue by nksaraf** [solidjs/solid-start#246]
Want to use this tool for doing storybook type development: https://histoire.dev/guide/getting-started.html. Needs solid support and then we can probably configure it for you

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
