### ISSUE TITLE
server function: esbuild Parse Error when running from tsx

### ISSUE THREAD

**Issue by btakita** [solidjs/solid-start#258]
When running a ts files using the `tsx` library, the ts files are built using esbuild.

```ts
import server from 'solid-start/server'
const my_fn = server(()=>{})
```

If the `server` function is in the build, a Parse Error occurs.

```
Error: Parse error @:1:2622
...
```

**Comment by nksaraf** [comment]
Why are we running files with server function with the `tsx` library.. it needs a server runtime to work? But also I would not expect a parse error.. must be because of the typescript.. its because we ship with typescript source which vite compiles.. `tsx` might not be transforming dependencies (most bundlers dont)

**Comment by btakita** [comment]
I have a monorepo & these functions were in a library. I was able to solve
the issue by moving those functions into the app.

Is it be possible to have a fallback where the server function returns it's
argument if it's called outside of vite?

**Comment by btakita** [comment]
If not, perhaps an explicit error? I had to track down the error through
process of elimination.

**Comment by ryansolid** [comment]
Hmm.. if the error is coming from `tsx` there isn't much way to get a better error. It's because `tsx` doesn't understand what it is looking at I gather. The server function does exist there and it just throws with a "Should be compiled away" error so this isn't a matter of stubbing it. We are hitting this at build time before anything runs.

This sort of outside of our purview because it is just a function being returned so this is more likely just a limit of how `tsx` executes or is configured. I don't see any more action from our side at this time.
