### ISSUE TITLE
todomvc:  Uncaught ReferenceError: $ROUTES_CONFIG is not defined on 

### ISSUE THREAD

**Issue by debpalash** [solidjs/solid-start#272]
`FileRoutes.tsx:4 `

```
// @ts-expect-error
var routesConfig = $ROUTES_CONFIG;
```

**Comment by jbanety** [comment]
This issue is raised when I add a call to `createServerData$`.

**Comment by yonran** [comment]
I ran into this issue too. That line `var routesConfig = $ROUTES_CONFIG;` comes from solid-start_server.js. The script that imported solid-start_server.js is `mypage.tsx?data`,

```js
import server$ from "/node_modules/.vite/deps/solid-start_server.js?v=e4e529f0";
```

According to [package.json](https://github.com/solidjs/solid-start/blob/4acc262b3b7fc13c75057316281b23ce680f9c93/packages/start/package.json#L59-L63), `import server$ from "solid-start/server";` should resolve to [browser.ts](https://github.com/solidjs/solid-start/blob/4acc262b3b7fc13c75057316281b23ce680f9c93/packages/start/server/browser.ts) instead of [server.ts](https://github.com/solidjs/solid-start/blob/4acc262b3b7fc13c75057316281b23ce680f9c93/packages/start/server/server.ts). I’m not sure why vite is serving the server.ts version at solid-start_server.js.

**Comment by nksaraf** [comment]
this required a variety of changes acrosss the tool chain, inlcuding `vite`, `vite-plugin-solid`, and `solid-start`. Should be fixed in:

`vite`: 3.1.2
`vite-plugin-solid`: 2.3.3
`solid-start`: 0.1.0-alpha.104

(Some of this will be released within the next few days)
