### ISSUE TITLE
Unable to find DOM nodes for hydration key when importing SVG into app.

### ISSUE THREAD

**Issue by 0xHexE** [solidjs/solid-start#281]
Hi,

I am getting issues when I am importing svg.

![image](https://user-images.githubusercontent.com/29942725/191680328-0d8b7917-abe2-49f8-80b9-c92a114ee857.png)

I have created a package for the icons at `@anthaathi/oracle-apex-solid-icons`.

When I am importing this component `IconReorderSmall`. I am getting this issue.

![image](https://user-images.githubusercontent.com/29942725/191680994-2e4fec5a-9bfd-4be5-9e3b-adca180ed74b.png)

**Comment by 0xHexE** [comment]
```jsx
export const IconReorderSmall = (props = {}) => <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16" {...props}>
<title>reorder</title>
<path d="M2.5 4h11c0.276 0 0.5-0.224 0.5-0.5s-0.224-0.5-0.5-0.5h-11c-0.276 0-0.5 0.224-0.5 0.5s0.224 0.5 0.5 0.5zM13.5 6h-11c-0.276 0-0.5 0.224-0.5 0.5s0.224 0.5 0.5 0.5h11c0.276 0 0.5-0.224 0.5-0.5s-0.224-0.5-0.5-0.5zM13.5 9h-11c-0.276 0-0.5 0.224-0.5 0.5s0.224 0.5 0.5 0.5h11c0.276 0 0.5-0.224 0.5-0.5s-0.224-0.5-0.5-0.5zM13.5 12h-11c-0.276 0-0.5 0.224-0.5 0.5s0.224 0.5 0.5 0.5h11c0.276 0 0.5-0.224 0.5-0.5s-0.224-0.5-0.5-0.5z"></path>
</svg>;
```

This is the code for the icon.

**Comment by ghalle** [comment]
Is the `Link` in the screenshot imported from `solid-start` by any chance? 

If so that's the `Link` tag from `@solidjs/meta` corresponding to a regular `<link>` tag. If you want the `Link` from `@solidjs/router` you'll need to either import `RouterLink` from `solid-start` or directly import it from `@solidjs/router`.

If not then could you please provide a repro for the bug, the `IconReorderSmall` by itself does not cause any issue and the code for the `Button` component was not shared. 

One last thing what versions of `solid-js` and `solid-start` did this issue occur with?
There have been some bug fixes related to SSR spread in the last few versions.

The lastest versions as of this post are:
```json
"solid-js": "^1.5.6",
"solid-start": "^0.1.0"
```

**Comment by 0xHexE** [comment]
I am running the latest versions of solid-js and solid-start. I think there is some issue. I found a workaround.

```ts
const c = children(() => <span>{props.children}</span>);
```

Related to https://github.com/solidjs/solid/issues/1242
