### ISSUE TITLE
useSearchParams() not returning query params within routeData().

### ISSUE THREAD

**Issue by phillipbaird** [solidjs/solid-start#321]
The example shown in the  **Fetching data based on search params** section of the [useSearchParams() docs](https://start.solidjs.com/api/useSearchParams) suggests we should be able to pass url query parameters to fetcher functions within routeData(). This does not seem to be working.
e.g.
```js
export function routeData() {
  const [searchParams] = useSearchParams();
  return createServerData$(async (query) => {
    return hogwarts.search(query)
  }, { 
    key: () => searchParams.query
  })
}
```
My use case is I'm wanting to use hrefs like `/?page=3` for paging.
Testing an example it appears the `searchParams` value is always `undefined`.
Note: This has been tried with `createRouteData` and `createServerData$`.

Should this example work?

Side note: useSearchParams() works as expected from within the component so am using that as a work around.

**Comment by ryansolid** [comment]
Yeah that is odd. Thanks for reporting.

**Comment by phillipbaird** [comment]
More info...
The docs example contains an error. The query parameters are being returned in searchParams not searchParams.query.

Passing searchParams as the key fixes the initial page load but subsequent navigation via <A> tags does not run the fetcher.
Console logging shows the key is being retrieved and the searchParams have the correct values.
A stacktrace suggests the problem is somewhere in the logic of solid-js/dist/server.cjs that decides whether or not to call the fetcher (somewhere near line 439).

The code for my routeData function can be viewed [here](https://github.com/phillipbaird/realworld-solidstart/blob/67ad41c935594f50ec4a4b11a41a913765e96d58/src/routes/index.tsx#L55).  If anyone wants to grab [this repo](https://github.com/phillipbaird/realworld-solidstart) as an example of the issue ensure you use the `useSearchParamBug` branch.

**Comment by nksaraf** [comment]
Okay solved the issue, and its stupidly intricate. So how the key works is you need to `read` all the reactive values you care about in that function and that tells us to rerun. 

In your current implementation, you `JSON.stringify(searchParams)` and return searchParams from the key. The return is not reading any reactive properties. So it doesn't create any dependency. The JSON.stringify will only read the currently exisiting properties of searchParams. So if the page you load has a query param like `?page=1`. It will rerun on `page=2`, but not on `tag=implementations` because JSON.stringify can't predict properties in the future. So nothing is actually subscribed to `searchParams.tag`

The solution was to explicitly read the searchParams that you want to react too. Even if they will start off as null, the fact that you read that property on `searchParams` will make sure when it is present, we have subscribed and we will rerun.

This is also why the example in the docs is  
```ts
export function routeData() {
  const [searchParams] = useSearchParams();
  return createServerData$(async (query) => {
    return hogwarts.search(query)
  }, { 
    key: () => searchParams.query
  })
}
```

The fact that we read `searchParams.query` means that we are subscribing to the `?query=abc` param. Not all the searchParams. So if you want to listen to another query param, like in your case, this is what you would need to do:

```ts
export function routeData() {
  const [searchParams] = useSearchParams();
  const articleData = createRouteData(fetchArticleData, {
    key: () => {
      console.log(`routeData(): searchParams = ${JSON.stringify(searchParams)}`);
      return {
        tag: searchParams.tag,
        page: searchParams.page,
        source: searchParams.source,
      };
    }
  });
}
```
