### ISSUE TITLE
Routes exporting both API endpoints and a component are not code split for client/server.

### ISSUE THREAD

**Issue by ghalle** [solidjs/solid-start#322]
This can cause issues when using dependencies that are not meant to be used on the client.

I suspect it might also leak the source for the API endpoints, but I have yet to confirm it.

We probably need to apply a babel transform to separate the API endpoints from the component.

**Comment by nksaraf** [comment]
yeah we just remove it from the client bundle

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
