### ISSUE TITLE
Integration with tRPC does not work

### ISSUE THREAD

**Issue by maksimsemenov** [solidjs/solid-start#334]
I was trying to use tRPC with solid-start. Here is a [repo with a reproduction example](https://github.com/maksimsemenov/solid-start-trpc): it is pretty simple, just a router with two procedures. But when I try to use it, I get a 404 error.

https://user-images.githubusercontent.com/3608139/196834810-6fb94ca9-6c56-4efe-bc5b-ab7999e9dedf.mov

**Comment by ghalle** [comment]
The endpoint in your `fetchRequestHandler` should match the path of the route. In `lib/trpc.ts` I can see that you defined the url as `/api/trpc` but you created a route directly in `routes/api/[...index].ts` this will match all of `/api/*` instead of only `/api/trpc/*`.

Try this instead:
`routes/api/trpc/[...trpc].ts`
```typescript
import { fetchRequestHandler } from "@trpc/server/adapters/fetch";
import { APIEvent } from "solid-start/api";
import { appRouter } from "~/lib/router";

const trpcHandler = (event: APIEvent) =>
  fetchRequestHandler({
    endpoint: "/api/trpc",
    req: event.request,
    router: appRouter,
    createContext: () => ({}),
  });

export const GET = trpcHandler;
export const POST = trpcHandler;
```

Also if you want to support SSR you will need some additional code to handle that. Let me know if you need help with that.

**Comment by maksimsemenov** [comment]
Ohh, thanks, it worked!
