### ISSUE TITLE
Static Generate Specific Routes

### ISSUE THREAD

**Issue by QuentinDutot** [solidjs/solid-start#381]
Is there a way to have SSG for some routes and CSR or SSR for other routes/directories? (e.g. an "app" folder)
Or any plan to support it in the future? I couldn't find the public roadmap for the v1

**Comment by nksaraf** [comment]
We don't have a proper roadmap yet. We are looking at options for route level control of these options.

**Comment by boehs** [comment]
#400

**Comment by ryansolid** [comment]
This is part of the next SolidStart Beta.

In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
