### ISSUE TITLE
Can't remove routeData from a module once added

### ISSUE THREAD

**Issue by viridia** [solidjs/solid-start#402]
I'm getting a funny routeData error: `Uncaught SyntaxError: The requested module '/src/routes/t.tsx?data' does not provide an export named 'routeData'` - thing is, that particular module doesn't use any route data, so there's no need for it. I guess I had routeData at one point and then deleted it later. Adding an empty routeData makes the error go away, but that's only a temporary workaround.

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
