### ISSUE TITLE
In MD and MDX, URLs for links and images have their query strings wrongly escaped

### ISSUE THREAD

**Issue by hmans** [solidjs/solid-start#410]
This breaks any link or image embed that has a URL with a query string that includes URL-escapable characters. (At the very least, it happens for ampersands. I haven't tested it with any other characters.)

It seems that both `.md` and `.mdx` documents are affected.

Example:

```md
[Link](http://test.com/foo?one=1&two=2)
```

will render to:

```html
<a href="http://test.com/foo?one=1&amp;two=2">Link</a>
```

while it _should_ render to:

```html
<a href="http://test.com/foo?one=1&two=2">Link</a>
```

[I've set up a minimal project that reproduces the issue](https://stackblitz.com/github/hmans/repro-link-escaping?file=src%2Froutes%2Findex.mdx).

It's impossible for me to tell if this is an issue with the `solid-mdx` or `solid-start-mdx` packages, or the framework itself (since this also happens in normal Markdown files.)

**Edit:** Updated to reflect the fact that it also happens in normal Markdown files.

**Comment by ryansolid** [comment]
This issue probably belongs in `solid-mdx` as `solid-start-mdx` just adds extra plugins. Since Solid Org doesn't own that I can't just transfer the issue. But I wanted to give you feedback as I am in the process of cleaning out this repo for the release of large rewrite.

In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
