### ISSUE TITLE
Tailwind classes not applying on save

### ISSUE THREAD

**Issue by statusunknown418** [solidjs/solid-start#439]
New tailwind classes added on a file are not visible on save (HMR), the page needs to be reloaded for them to be applied.

**Comment by ryansolid** [comment]
Is this something specific to Tailwind? Do they have a compilation step perhaps that races our HMR?

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
