### ISSUE TITLE
Static Site Config hosting on Netlify

### ISSUE THREAD

**Issue by talves** [solidjs/solid-start#440]
Using the SSG configuration for Netlify.

`vite.config.ts`
```js
import solid from "solid-start/vite";
import { defineConfig } from "vite";
import staticAdapter from "solid-start-static";

export default defineConfig({
  plugins: [
    {
      ...(await import("@mdx-js/rollup")).default({
        jsx: true,
        jsxImportSource: "solid-js",
        providerImportSource: "solid-mdx",
      }),
      enforce: "pre",
    },
    solid({
      // ssr: false,
      extensions: [".mdx", ".md", ".tsx"],
      prerenderRoutes: ["/index", "404"],
      adapter: staticAdapter(),
    }),
  ],
});
```

## Error
![image](https://user-images.githubusercontent.com/784848/201720150-d8815d8a-9c16-4ffa-a8f6-83da1e913689.png)

![image](https://user-images.githubusercontent.com/784848/201718734-74bcf56c-1720-4358-b6e3-47d0fc9a6bd0.png)

## Site Code
https://github.com/talves/solid-mdx-tailwind-template

## Netlify Site

https://solid-mdx-template.netlify.app/

**Comment by ryansolid** [comment]
This appears to be a hydration error.

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
