### ISSUE TITLE
[packages start-netlify]: Fix `_redirects` to check for existing file or netlify.toml config

### ISSUE THREAD

**Issue by talves** [solidjs/solid-start#441]
Currently the `packages/start-netlify` adapter doesn't allow for additional redirects in the same site deploy.

If a site uses the netlify email plugin or functions, the path is redirected to the app routes only. The developer should be able to add those redirect paths prior to the app overwrite paths at root.

## Example `_redirects` (published)

```
/.functions/email/* /api/:splat 200!
/*    /.netlify/functions/index    200
```

An initial solution could just be as simple as allowing a `_redirects` file at the root of the repository to be copied to the deploy/distribution folder. Also a check for redirects in a netlify.toml would allow for the ability to create headers for proxy redirects. If the `netlify.toml` file exists, skip the `_redirects` write and make sure there is a proxy rewrite for the app equivalent.

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
