### ISSUE TITLE
Error inside createRouteAction not triggering ErrorBoundary

### ISSUE THREAD

**Issue by dallastjames** [solidjs/solid-start#445]
[In the documentation](https://start.solidjs.com/core-concepts/actions#errors), it's mentioned that if you don't explicitly handle an error on a route action then the error should bubble up to the nearest ErrorBoundary:
![CleanShot 2022-11-15 at 14 00 01](https://user-images.githubusercontent.com/16655763/202014135-ff8aa227-fc69-4135-9e00-4fd2f2a1fee8.png)

Given the following two components:

```tsx
export function FormSection() {
  return (
    <ErrorBoundary fallback={() => <h2>Oh no! Error!</h2>}>
      <TinyForm />
    </ErrorBoundary>
  );
}
```

```tsx
export function TinyForm() {
  const [formState, { Form }] = createRouteAction(async (data: FormData) => {
    throw new Error("Something went wrong!");
  });

  return (
    <Form>
      <label for="username">Username:</label>
      <input type="text" name="username" />
      <input type="submit" value="submit" disabled={formState.pending} />
    </Form>
  );
}
```

I would expect that the error being thrown in the route action bubbles up to the `ErrorBoundary` above, but it is not. The error is just swallowed by the routeAction. I can still manually handle errors using the recommended approach:

```tsx
<Show when={formState.error}>
  <p>Oh no, there was an error: {formState.error.message}</p>
</Show>
```

But ideally, I'd like to ensure that these hit the Error boundaries as expected so that I can ensure I'm catching unhandled errors inside of Sentry.

[A sample app with a reproduction lives here](https://github.com/dallastjames/solid-start-route-action-error-boundaries)

**Comment by ryansolid** [comment]
Yeah I think this was changed at some point before beta release and the docs need to update to reflect this. Relying on a property access made that very difficult, especially with things like multi-actions. The criteria to fickle. And almost never what you'd want since it would unmount the form most likely as it had to be tied to where the action was defined rather than to where it is used. Patterns used for Suspense didn't really make sense here. 

At this point I think I'd say this is a documentation issue. We could try to revisit it but this is a very different type of primitive since it is basically ephemeral so it doesn't tie into the this is needed to render the UI pattern that made ErrorBoundaries a thing in the first place.
