### ISSUE TITLE
[start-cloudflare-pages] Generate _routes.json to exclude static routes

### ISSUE THREAD

**Issue by shmshd** [solidjs/solid-start#452]
When using `start-cloudflare-pages` adapter, all requests by default will invoke Cloudflare Function which will ramp up the daily limit. To avoid static assets to invoke CF Function, as per their docs, frameworks should generate ` _routes.json` file.

https://developers.cloudflare.com/pages/platform/functions/routing/#function-invocation-routes

**Comment by shmshd** [comment]
Example `_routes.json` file would be:
```json
{
   "version": 1,
   "include": ["/*"],
   "exclude": ["/assets/*"]
}
```
which will ignore all assets to go through CF Function.
As per the docs, this should be in the `dist/public` folder.

**Comment by marbemac** [comment]
Just a note, for now you can just put that `_routes.json` file in the `public` folder, and it'll be copied to the correct spot (`dist/public`) during the build step.

**Comment by shmshd** [comment]
@marbemac yes, I already mentioned this in https://github.com/solidjs/solid-start/issues/452#issuecomment-1319129075. When using an adapter specific to a platform, developers expect all kinds of quirks to be managed by that adapter.

**Comment by serban-mihai** [comment]
Since the `/dist/public/assets/*` contains all the app code that has compiled at build time with unique names how can we predict which files we shall exclude from Workers invokes?

If I have a route for `mydomain.com/terms-and-services` which it's static by definition (I don't want to invoke any worker call on it because its content isn't dynamic) after the build will be generated with the name `/dist/public/assets/terms-and-services.e65d43ftr.js` making it impossible to map to the `"exclude": []` property in `_routes.json` that just gets copied to **dist** from the **public** directory.

How can we exclude specific routes from triggering workers uselessly?

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
