### ISSUE TITLE
Title not updated properly on client side navigations if whole HTML tree got suspended

### ISSUE THREAD

**Issue by pawelblaszczyk5** [solidjs/solid-start#460]
I've got resource that I'm using to retrieve user's color scheme preference and I'm suspsending whole HTML tree to update the class and styles on root element while SSRing. I noticed that on client side navigations the title is not properly updated. The old one is not removed from the head, hence the new even if appended is not applied. It can probably create more issues than mine. 

Reproduction: [StackBlitz](https://stackblitz.com/edit/vitejs-vite-zygwoz?file=src/root.tsx) or [repo](https://github.com/pawelblaszczyk5/solid-start-title-reproduction )

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
