### ISSUE TITLE
Fetch failed

### ISSUE THREAD

**Issue by intermundos** [solidjs/solid-start#467]
Hello all!

I have this code block

```
export function routeData() {
    return createServerData$(
        async key => {
            const response = await fetch( `http://localhost:9000/some` )
            return ( await response.json() )
        }
    )
}
```

When visiting the page I get following error 
![Screen Shot 2022-11-21 at 19 56 31](https://user-images.githubusercontent.com/16274871/203126720-4ed56ee1-90c3-462a-8e7c-904bbbe3352a.png)

This is what I get in terminal
![Screen Shot 2022-11-21 at 20 06 35](https://user-images.githubusercontent.com/16274871/203128591-1e4496fa-3569-48e3-9b38-c4cd5ad64dc3.png)

Tried to fetch with `createRouteData` but no luck either. I am using Mockoon that is running at port 9000. Doing fetch on client works without problems.

Would appreciate any help. Thanks!

**Comment by ryansolid** [comment]
Fetch to localhost can be tricky. Security policies on your machine can prevent it. Apparently, the other program is rejecting our fetch and you might have to look there.

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
