### ISSUE TITLE
Windows: `docs:dev` in monorepo fails

### ISSUE THREAD

**Issue by emilbonnek** [solidjs/solid-start#489]
I tried running the docs locally in order to suggest some changes in there, but got this error
![solidstart_docs_error](https://user-images.githubusercontent.com/6923755/204358584-80b00994-b786-4c0c-a56e-4bee1ce42246.png)

Are there some issues with the docs project or am I missing something?

**Comment by ryansolid** [comment]
I'm not seeing that exact error but I am seeing an issue with the docs build right now. Thanks for reporting.

**Comment by emilbonnek** [comment]
It very well could just be Windows resolving paths differently. I don't have a way to test on another system unfortunately. The import it can't resolve is at: `/componentsTableOfContents.tsx` - I am guessing that should have been `/components/TableOfContents.tsx`? It seem like the `/` is getting stripped away then.


I attempted moving `TableOfContents.tsx` from `/components` into `/components/testfolder` and then I get the following error:
![127 0 0 1_3000_core-concepts_routing](https://user-images.githubusercontent.com/6923755/204640951-9c3ade3a-2346-41a0-bac6-38e07207b2e7.png)
Here it is unable to resolve the import at `/componentsestfolderTableOfContents.tsx`. it now seems to strip both the `/` and the leading 't' off 'testfolder' as well as the another `/` before the filename.

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
