### ISSUE TITLE
[enhancement] Add the ability to select multiple integrations in the CLI

### ISSUE THREAD

**Issue by orenelbaum** [solidjs/solid-start#496]
Right now the options in the CLI are `bare`, `hackernews`, `todomvc`, and other than that all the other options are different integrations.
However, since every integration is its own template you can choose only one, but other than the Tailwind and solid-styled integration none of them collide, so it's very likely users would want to choose multiple integrations.
So I think it would be helpful if we could give users the ability to choose multiple integrations. Maybe the `bare`, `hackernews` and `todomvc` options should have their own templates sub-menu in which you can't choose integrations, and all the other options should be in an integrations sub-menu which enables multiple choices.

**Comment by atk** [comment]
I too would prefer integration classes, i.e. an option for styling (tailwind, vanilla extract, uno-css, solid-styled, CSS modules), testing (vitest, jest, uvu, none), linting (eslint+solid plugin, none), etc.

**Comment by thislooksfun** [comment]
You might be able to use [create-jd-app](https://github.com/OrJDev/create-jd-app) as a starting point. It doesn't have a LICENCE, but it's based off the t3 stack which is MIT.

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
