### ISSUE TITLE
Change the color of the red text in the CLI

### ISSUE THREAD

**Issue by orenelbaum** [solidjs/solid-start#513]
When running the CLI, it shows this text in red:
```
Welcome to the SolidStart setup wizard!

There are definitely bugs and some feature might not work yet.
If you encounter an issue, have a look at https://github.com/solidjs/solid-start/issues and open a new one, if it is not already tracked.
```
The red color makes it seems like there is an error. Any other color will probably be better.
Maybe the 2 bottom lines should be yellow since they are a warning.

**Comment by dayvster** [comment]
Would Cyan or Blue be a better choice here? 
Also since it's been in enhancement since December, mind if I take this one?

**Comment by ryansolid** [comment]
There will be a new CLI released in the next few days with the new beta.

In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.

**Comment by uncenter** [comment]
> There will be a new CLI released in the next few days with the new beta.

Are you referring to https://github.com/solidjs-community/solid-cli, or something else? If not, this is still relevant.
