### ISSUE TITLE
Trouble deploying a static site to a domain subfolder

### ISSUE THREAD

**Issue by viridia** [solidjs/solid-start#514]
I am having trouble trying to deploy a static site to github pages. Because github locates the pages until a subdirectory in the url, I need to set the "base" location - I can do this in Vite with the `base` option, but when I attempt to do the same to the solid "Routes" component things go haywire. I get "Unrecoverable Hydration Mismatch".

(Not setting the base option in the Routes means that navigation links go to the root folder, which 404s because there is no page there.)

**Comment by LiQuidProQuo** [comment]
https://github.com/solidjs/solid-start/pull/742  may fix this issue

**Comment by atk** [comment]
I have [documented the process](https://dev.to/lexlohr/using-solid-start-with-github-pages-3iok).

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
