### ISSUE TITLE
Hydration bug (build only) with components from linked dependency

### ISSUE THREAD

**Issue by aeplay** [solidjs/solid-start#522]
I kept running into hydration issues in my production build of a mostly static site based on the `with-tailwind` template (SSR yes, TS yes). Dev server always works fine.

The only thing that seems special about my setup is that I import some components from a linked dependency in the same monorepo (using "link:../component-lib" syntax in package.json).

When I manually pull in the components so they're just local, the production build hydrates correctly.

I created a minimal reproduction of the whole setup in https://github.com/aeplay/solid-start-linked-hydration

You can toggle between the two scenarios by un/commenting these lines:

https://github.com/aeplay/solid-start-linked-hydration/blob/3049243436f523111fd550b2d0ccec0d196e82cc/app/src/routes/index.tsx#L1-L7

This is what the dev server renders (`yarn dev`):

<img width="1552" alt="Screen Shot 2022-12-06 at 14 26 41 014" src="https://user-images.githubusercontent.com/1593585/205942026-c9af2e88-50c6-4eff-82cb-fad3b53251e1.png">

This is what happens in the production build (`yarn build && yarn start`)

<img width="1552" alt="Screen Shot 2022-12-06 at 14 26 23 730" src="https://user-images.githubusercontent.com/1593585/205940787-18974bc0-e3a6-4cac-8f7b-5079f000e7a2.png">

As you can visually see, on hydration, it seems to insert a copy of the preceding `MiniStory` container into the `<em>` element inside the `MiniStory`s that contain an `<em>`. (Before hydration, the server-rendered HTML looks correct)

In my more complex actual app, I also get lots of errors trying to read `nextSibling` of `null`, I guess this minimal scenario is a lucky one where hydration actually finds another (albeit wrong) element to attach to.

Since this differs between dev and build and is related to dependencies, I wonder if this is a side-effect of #127 ?

Thank you for your help.

**Comment by marbemac** [comment]
Hmm - setting `dev: true` in the vite config causes the issue to disappear, although I'm not sure what implications are for prod build 🤔.

<img width="936" alt="Screenshot 2023-01-12 at 2 41 48 PM" src="https://user-images.githubusercontent.com/847542/212165102-a02ea437-5f3f-44ce-99f6-da23fea6fe42.png">

**Comment by ryansolid** [comment]
There is a lot of awkwardness with optimize deps and not which led us to use a plugin created for SvelteKit to walk through dependencies and find which ones have Solid JSX etc.. I'm gathering link completely is ignored by this walk.

We needed to do this all originally because we needed to set JSX to optimize to dedupe but needed to have the specific files all reject other ESBuild would output React JSX. We now in SolidStart have a Solid ESBuild plugin so ESBuild works fine. Maybe we need to just always package ESBuild Solid with our Vite plugins.

**Comment by marbemac** [comment]
Yeahh, and in fact `optimizeDeps` ended up resulting in a separate issue. The shared component lib has `solid-js` in it's dependencies (same version as the app itself), which perhaps is resulting in multiple solid-js getting included, not quite sure TBH. Digging in a bit more.

<img width="638" alt="Screenshot 2023-01-13 at 3 56 44 PM" src="https://user-images.githubusercontent.com/847542/212417580-cecc6f26-94e5-4bff-815d-7f56b0e00992.png">

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
