### ISSUE TITLE
Enhanced anchor tags not working with bootstrap tab group

### ISSUE THREAD

**Issue by birkskyum** [solidjs/solid-start#526]
I have a very basic bootstrap [nav tab group like this](https://getbootstrap.com/docs/4.0/components/navs/#tabs), and I noticed it breaks when using "A" instead of "a" tags, but I can't see any mentions in the docs of when *not* to use A tags if it's by design.

This is just two tabs:

```ts
<ul class='nav nav-tabs' id='myTab' role='tablist'>
  <li class='nav-item'>
    <A
      class='nav-link active'
      id='home-tab'
      data-toggle='tab'
      href='#home'
      role='tab'
      aria-controls='home'
      aria-selected='true'
    >
      Current system and assets
    </A>
  </li>
    <li class='nav-item'>
      <A
        class='nav-link'
        id='profile-tab'
        data-toggle='tab'
        href='#profile'
        role='tab'
        aria-controls='profile'
        aria-selected='false'
      >
        Plan new agroforestry system
      </A>
    </li>
</ul>
```

Normal <a> tags = Working
<img width="529" alt="Screenshot 2022-12-09 at 20 33 56" src="https://user-images.githubusercontent.com/74932975/206783664-a3b0469c-6395-47b7-950e-4b3c67b7f044.png">

Enhanced <A> tags = Not working
<img width="534" alt="Screenshot 2022-12-09 at 20 34 08" src="https://user-images.githubusercontent.com/74932975/206783566-4f6426ba-c9ef-4ee0-9473-6ce75f3b66fe.png">

**Comment by ryansolid** [comment]
All capital `<A>` does is use Solid's router instead of native browser behavior.  That being said hashes should pass through. I see from the image the link doesn't appear highlighted. But given `<A>` is just a `<a>` I wouldn't expect any style issues. So unclear what's up from what I'm looking at. But then again you aren't really using Solid's router so lowercase `<a>` is probably fine.

**Comment by birkskyum** [comment]
Great, then <a> it is.
