### ISSUE TITLE
Solidjs Mdx: createRouteData and useRouteData didn't work

### ISSUE THREAD

**Issue by ThanhDat-Vo** [solidjs/solid-start#546]
### Describe the bug

createRouteData and useRouteData didn't work in Solidjs Mdx
1. the value return from useRouteData is undefined 
2. typescript could not work in mdx

### Your Example Website or App

https://stackblitz.com/edit/github-n9s1u9-fhe7sw?file=src%2Froutes%2Findex.mdx

### Steps to Reproduce the Bug or Issue

1. fetch https://github.com/solidjs/solid-start/tree/main/examples/with-mdx
2. add createRouteData and useRouteData to index.mdx
3. remove all type declaration for createRouteData and useRouteData 
4. try to print value return from useRouteData()
5. got error

### Expected behavior

createRouteData and useRouteData should work in index.mdx
and typescript should not return any error

### Platform

- OS: macOS
- Browser: Chrome
- Version: latest

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
