### ISSUE TITLE
Every (frequent) change from data in createResources causes several issues

### ISSUE THREAD

**Issue by djmin43** [solidjs/solid-start#547]
### The logic I am trying to get is pretty simple:

- A user searches a file/dir by its name in the input field
- Whenever there is a change in the input field, api gets called and searches for any matching file/dir names

### This is the environment I am trying out:

- Instead of actual api from backend server, I created a small api.ts file for testing that acts like a server
- Using createResource to fetch data whenever there is a change in searchInput

### Issues:

- Whenever there is a change in the input field, it loses focus. 
- Because it loses focus, I can't test if it's just slowness or rendering issue

### What I found so far:

- it loses focus ONLY when I want to **render** the result from the search. It probably means calling every input change is not an issue actually.
- If I don't render the result, fetching the data works really well.
- I thought it was a solidjs issue for some time. But this code works well in Solidjs. Only happening in Solidjs start.

Please see the code and ui below for the issue.

```ts
import Api from "../api/api";
import { createResource, createSignal, For } from "solid-js";

const fetchDir = async (name: string) => {
  return await Api.searchByName(name);
};

export default function Home() {
  const [searchInput, setSearchInput] = createSignal("");

  const [query] = createResource(searchInput, () => fetchDir(searchInput()));

  const onInput = (event: unknown) => {
    setSearchInput(event.currentTarget.value);
  };

  return (
    <main>
      <label>file:</label>
      <input type="text" value={searchInput()} onInput={(e) => onInput(e)} />
      <For each={query()}>{(item) => <p>{item.name}</p>}</For>
    </main>
  );
}
```

![Screenshot 2022-12-18 at 7 18 52 PM](https://user-images.githubusercontent.com/75886558/208292896-01a3ec89-892f-4dac-896f-7a55208d1616.png)

**Comment by ryansolid** [comment]
Yeah I don't see any issue that would cause input to lose focus just looking at the code. Can you confirm if the Home component is re-rendering? Put a console.log in the component body and see if calls. For the input to lose focus it suggests that the input element is getting unmounted for some reason. But nothing in the component suggests that should be the case.

**Comment by djmin43** [comment]
Thanks for the quick reply, Ryan.

I realized the next day the code itself won't give enough information about this issue really. I will give a more thorough research this weekend if it is actually re-rendering or some other possible issue.

Cheers.

**Comment by lordnox** [comment]
Hi, I just stumbled upon the same issue.

Here is some code that will replicate it: https://playground.solidjs.com/anonymous/ea47f1ed-e35a-439e-9e8d-566e7fe7e999

Just copy the `App.tsx` into some solid-start project, only the async - createResource case will rerender the page and cause the issues.

**Comment by djmin43** [comment]
I added console log to see if it is actually re-rendering, and gladly it's not the case.

I am guessing the actual problem is that it loses focus when there's a change in input WHILE there's state (from creatSignal) being rendered.

I will create a replicate code in the playground as @lordnox did. Thanks for the idea.

**Comment by djmin43** [comment]
OK, I found out what's causing the problem.

I attached the code you can simply copy and paste to your solidjs start boilerplate to reproduce the bug. Whenever I put 'async' in function, it causes the problem (going out of focus).

I understand this is definitely not a common way of writing an app. I happened to use this method while creating an interview question for the company I work for. However, I thought I'd raise an issue as Solidjs Start is in a very early stage.

I will take some time to research the reason. Please add comments if there's anything I am doing wrong -- I am really new to Solidjs.

### Solidjs start setup
- *y* to SSR
- *y* to Typescript
- bare solidjs

### package.json
```ts
{
  "name": "bug-reproduction",
  "scripts": {
    "dev": "solid-start dev",
    "build": "solid-start build",
    "start": "solid-start start"
  },
  "type": "module",
  "devDependencies": {
    "solid-start-node": "^0.2.0",
    "typescript": "^4.8.4",
    "vite": "^3.1.8"
  },
  "dependencies": {
    "@solidjs/meta": "^0.28.0",
    "@solidjs/router": "^0.6.0",
    "solid-js": "^1.6.2",
    "solid-start": "^0.2.0",
    "undici": "^5.11.0"
  },
  "engines": {
    "node": ">=16.8"
  }
}
```

### code that reproduces bugs (no code change elsewhere)

```ts
// src/routes/index.tsx

import {createResource, createSignal, JSX} from "solid-js";

const fetchChar = (value: string) => {
    return api.findChar(value)
}

export default function Home() {

    const [searchInput, setSearchInput] = createSignal("")

    const [query] = createResource(searchInput, () => fetchChar(searchInput()))

    const onInput: JSX.EventHandler<HTMLInputElement, InputEvent> = (event ) => {
        setSearchInput(event.currentTarget.value);
    };

  return (
    <main>
        <h1>bug reproduction</h1>
        <label>file:</label>
        <input type="text" value={searchInput()} onInput={onInput} />
        {query()}
    </main>
  );
}

const charList = ["a", "b", "c", "d", "e"]

const api = {
// PROBLEM: here 'async' is causing the problem.
    findChar: async (value: string) => {
        return charList.find(element => element === value)
    }
}
```

### Solidjs Playground exmaple
* Proof that it works in solidjs no problem: https://playground.solidjs.com/anonymous/15d908e8-4e3e-4c1a-94dd-84bfe5d03ab4

**Comment by djmin43** [comment]
Cool to see new tags by the way!

**Comment by djmin43** [comment]
Same issue happening with api from actual backend server.

**Comment by ryansolid** [comment]
Yeah something odd is going on here and it only happens with SSR. The whole parent is remounting (but not re-running the component). Probably a Solid core bug. Thanks for the reproduction.

**Comment by ryansolid** [comment]
Sorry on more investigation I realized this wasn't a bug. Unlike the playground the app is wrapped in a Suspense boundary. Whenever you read a resource that hasn't loaded it will trigger Suspense and will go back to fallback.. in this case it happens to be nothing. To solve this there are a few options. Removing Suspense probably isn't one of them since we want to handle Async in SSR.


There are 3 ways to handle this so I'm going to describe them for the different people who might come across them.

What you can do is add another Suspense boundary closer not wrapping the input and just the query and have it provide loading state. Now whenever Query changes it will show a loading state and not affect the rest of the UI.

```js
<main>
  <h1>bug reproduction</h1>
  <label>file:</label>
  <input type="text" value={searchInput()} onInput={onInput} />
  <Suspense fallback="loading">{query()}</Suspense>
</main>
```
Alternatively if you want to continue to show the stale data but synchronize updates so they show consistently you can wrap update in a `Transition`. You can use `useTransition` or `startTransition`. This can even give you an indicator when it's loading. Transitions are valuable when you don't want to show inconsistent data.. like the text not matching the search results (although it will in this case since you are typing into the input directly). It will wait to update all signals until everything async is committed. We use this a lot for things like routing.
```js
const onInput: JSX.EventHandler<HTMLInputElement, InputEvent> = (event ) => {
      const v = event.currentTarget.value
      startTransition(() => setSearchInput(v));
 };
```

Finally for this case what you probably want is tearing because you want the input to update immediately and are ok with the search results being out of date. And you can achieve with using `.latest` on the resource. This will read the latest value rather than trigger Suspense as long as it has settled once.

```js
<main>
  <h1>bug reproduction</h1>
  <label>file:</label>
  <input type="text" value={searchInput()} onInput={onInput} />
  {query.latest}
</main>
```
I apologize for the confusion. I am sort of regretting letting resources work without Suspense boundaries right now given it creates confusing expectations, when the primitive is designed specifically for Suspense.

**Comment by Feel-ix-343** [comment]
I ran into this bug with ssr set to false (though ryan said it is a ssr bug). This relates to the other issue where solid start doesn't work without ssr in dev mode? But anyway I just removed suspense and there is no more lag on my app.

**Comment by mydracula** [comment]
It is very unfriendly for beginners to encounter this problem. I originally wanted to try solidstart, but because of this problem, it was difficult to check my own code for a long time. I didn't lose focus but the page was refreshed, but anyway it was because of an empty fallback of Suspense in root.tsx
