### ISSUE TITLE
Fresh install with Yarn = "vite: command not found"

### ISSUE THREAD

**Issue by milesj** [solidjs/solid-start#558]
Just scaffolded a Solid app using Yarn 3 and the `dev` script fails with "/bin/sh: vite: command not found".

Relying on `spawn` knowing where bins are isn't very effective: https://github.com/solidjs/solid-start/blob/main/packages/start/bin.cjs#L122

**Comment by danieltroger** [comment]
I too would love to use yarn 3 with solid-start

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
