### ISSUE TITLE
Tailwindcss+VercelAdapter not building

### ISSUE THREAD

**Issue by dayblox** [solidjs/solid-start#566]
Minimal reproduction:

```sh
pnpm create solid # with-tailwindcss - SSR - TS
pnpm i
pnpm i -D solid-start-vercel
```

```diff
  # vite.config.ts
  import solid from "solid-start/vite";
  import { defineConfig } from "vite";
+ import vercel from "solid-start-vercel";
  
  export default defineConfig({
-   plugins: [solid()],
+   plugins: [solid(vercel())],
  });
```

```sh
pnpm build
```

> Circular dependency: node_modules/.pnpm/undici@5.14.0/node_modules/undici/index.js -> node_modules/.pnpm/undici@5.14.0/node_modules/undici/lib/fetch/index.js -> node_modules/.pnpm/undici@5.14.0/node_modules/undici/index.js

**Comment by ryansolid** [comment]
Does this actually prevent you from building? I see it too. It looks like undici references itself in a circular way but it doesn't appear to affect my ability to build the code. This one looks to be out of our hands that's why I'm asking.

**Comment by dayblox** [comment]
You are right, I can't seem to reproduce and it seems to build regardless of the circular dependency, my bad!

**Comment by ryansolid** [comment]
Hmm.. the start command appears to be wired to the vercel command which will prompt some CLI stuff. I think this error is saying you don't have the vercel CLI installed (or it can't find it). You can try typing vercel in the terminal and seeing if it is installed. If not, try:

```sh
pnpm i -g vercel
```
And run start command again. I think start doesn't do anything for the vercel adapter other than deploy because there isn't a way to run it locally.

**Comment by dayblox** [comment]
You are probably right since I did not have the vercel CLI installed.
I just tried to reproduce and couldn't, is the circular dependency gone and how is it linked to the need for the vercel CLI?

**Comment by dayblox** [comment]
Nevermind, the circular isn't gone, but the adapter syntax seems to have changed
from
```JS
  plugins: [solid(vercel())],
```
to
```JS
  plugins: [solid({ adapter: vercel() })],
```

**Comment by dayblox** [comment]
I installed the vercel CLI as you suggested and still get the exact same error 😢

**Comment by andrewrosss** [comment]
For anyone finding this, I just started a project with the tailwind starter and got this circular dependency warning.

It doesn't appear to break the build. So as long as the `solid-start-vercel` adapter is installed in your project (and setup in your `vite.config.ts`) I think this warning can be ignored.

Regarding the `pnpm start` error, when trying to run `pnpm start` (after running `pnpm build` locally) I was getting the exact error in the [comment above](https://github.com/solidjs/solid-start/issues/566#issuecomment-1372865047).

I installed the vercel CLI (`npm i -g vercel`) and then logged into my vercel account (`vercel login`), and the error disappeared.

Of course, your experience may differ, but this worked for me.

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
