### ISSUE TITLE
 Dev mode: imported css file in route page is applied globally (every page)

### ISSUE THREAD

**Issue by aquaductape** [solidjs/solid-start#579]
This issue happens in development mode, not in production output

1. create new project
```
mkdir my-app && cd my-app
pnpm create solid

# cli 
> bare
> serverside rendering Yes
> use typescript Yes
```
2. Add css file `home.css` in routes and import it in `home.tsx` file.

<img width="260" alt="Screen Shot 2022-12-23 at 11 48 19 AM" src="https://user-images.githubusercontent.com/29286430/209399858-488267f0-83f7-493e-8852-4c2f45caf380.png">

`home.tsx`
```jsx
import "./home.css";
const Home = () => {
  return <div>home</div>;
};

export default Home;
```
`home.css`
```css
body {
  background: red;
}
```

3. visite root page, or foo route or 404 route and the style from `home.css` is present
<img width="354" alt="Screen Shot 2022-12-23 at 11 51 42 AM" src="https://user-images.githubusercontent.com/29286430/209400160-0fdff39f-6836-451d-93a6-5301af3cc37c.png">

## What did I expect to happen?

For the style from `home.css` to only apply to `home` route, not on all pages

**Comment by pawelblaszczyk5** [comment]
Afaik, it will happen in prod (but a little differently) as well if you navigate between pages. Generally, css imports like that are side effects. You could import as an url and use the `Link` I think 🤔

**Comment by ryansolid** [comment]
Funny enough this is super common in most metaframeworks but I believe we handle this better in the new beta.

In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
