### ISSUE TITLE
Support for next middleware function

### ISSUE THREAD

**Issue by btakita** [solidjs/solid-start#59]
This will allow the `solid-start` middleware to be bypassed to the next middleware.

`entry-server` can take a `next` param which will enable it to move to the next middleware.

**Comment by btakita** [comment]
I was able solve my use case by making ApolloServer lazy load:

```js
function graphql_plugin_(path) {
	/** @type {import('vite').ServerHook} */
	const configureServer = async server=>{
		/** @type {import('apollo-server-express').ApolloServer<any>} */
		let apollo
		/** @type {import('express').Router} */
		let router
		server
			.middlewares
			.use(async (req, res, next)=>{
				if (!apollo) {
					const { typeDefs, resolvers } = await server.ssrLoadModule('@censible/service-domain')
					apollo = new ApolloServer({
						typeDefs,
						resolvers,
						plugins: [ApolloServerPluginDrainHttpServer({
							httpServer: server.httpServer
						})],
					})
					await apollo.start()
					router = apollo.getMiddleware({
						path
					})
				}
				router(req, res, next)
			})
	}
	return { configureServer }
}
```

**Comment by nksaraf** [comment]
The issue with something like this is that now you have to figure out how to integrate this into the adapters since they don't use vite middleware to build their server.. so doing stuff with the vite server creates a split where u need to setup the build step and dev step separately. Maybe we can brainstorm how to do this from within entry-server itself without involving vite.

**Comment by btakita** [comment]
In the case of Apollo, there's a different adapter for each platform. I don't know if having to support the dev & prod adapters separately is avoidable. Making it easier to manage by creating the right abstractions to handle each platform seems doable & will form a base layer if a common interface can be created.

**Comment by nksaraf** [comment]
We do want to enable you to use platform specific primitives where you want, and you would be consciously opting out of universal deployment for that app. I see Cloudflare workers KV or Durable Object beings examples of this. But I don't think the vite config is the correct place for this since that's working in dev only. In prod your entry-server is the main place to initialize these things. including lazy loading via dynamic imports.. 

Could you try what this might look like via a dynamic import in `entry-server`. We do support middleware in there so this might work. 

Closing this for now, but you can open it again if things don't work as you want!
