### ISSUE TITLE
Text content is doubled when using pure text inside Suspend or ErrorBoundary fallback (only with renderStream)

### ISSUE THREAD

**Issue by Hubro** [solidjs/solid-start#593]
```tsx
<Suspense fallback="Loading...">
  <ErrorBoundary fallback={(e) => <>Oh no, we crashed: {e}</>}>
    <Show when={statusResource()}>
      Deployment: {statusResource()!.name}
    </Show>
  </ErrorBoundary>
</Suspense>
```

![image](https://user-images.githubusercontent.com/597206/209551824-4b5a25cb-8124-4fc5-958e-eea78bb37f30.png)

![image](https://user-images.githubusercontent.com/597206/209551894-1228fd8e-9827-4f00-b6ae-4a2ad8760505.png)

There seems to be a race condition here, if I spam refresh then sometimes the text is not doubled, perhaps depending on whether the content needed to be streamed or if it was fetched quickly enough to be included in the initial HTML (?)

Wrapping the text in HTML elements, such as `<p>Deployment: {statusResource()!.name}</p>` and `<p>Oh no, we crashed: {e}</p>`, fixes this issue.

Demo:

https://user-images.githubusercontent.com/597206/209549106-be6e7ab9-4641-40d3-9e5d-1f7ba5627a05.mp4

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
