### ISSUE TITLE
[Bug] with ssr false, stylesheets imported in root.tsx are only applied when directly visiting route /

### ISSUE THREAD

**Issue by vanillacode314** [solidjs/solid-start#614]
Issue: With ssr false, stylesheets imported in root.tsx are only applied when directly visiting route / and not any other route like /about, This only occurs in build and not in dev.

Repro Github: https://github.com/vanillacode314/no-ssr-css-import-bug-solid-start-repro
Repro Steps: 

1. Build the app and start the server
2. Visit any route other than / in this repo /settings

**Comment by Somft** [comment]
After some digging, I think the issue lies in the `packages/start/root/Links.tsx`. After building my project with `ssr: false` Links function in server.js returns null, which causes links to be empty.

After changing Links function to look like below, everything works fine.
```
export default function Links() {
  const isDev = import.meta.env.MODE === "development";
  const context = useContext(ServerContext);
  if (!isDev) {
    if (import.meta.env.START_SSR) {
      useAssets(() => getAssetsFromManifest(context!.env.manifest, context!.routerContext!));
    } else {
      return <link rel='stylesheet' href={context.env.manifest?.["index.html"][1]?.href} />
    }
  }
  return null;
}
```

This solution works for me, but I don't know if it takes into account all possible conditions. 

It is worth to mention that, it is possible to serve public directory by nginx (as i'm doing) and problem doesn't occur.

**Comment by vanillacode314** [comment]
can confirm this fix works for my app too

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
