### ISSUE TITLE
Setting host to 0.0.0.0 and accessing trough custom ip address fails register code changes

### ISSUE THREAD

**Issue by Defex** [solidjs/solid-start#617]
Hi, So I have tried out multiple starter templates and all come with the same problem. 

My server lives in a different machine which requires me to access it trough a custom port such as `192.168.1.1`

so I updated my `dev` script:
```
    "dev": "solid-start dev --host 0.0.0.0",
``` 

But whenever I edit the `root.tsx` file by adding a new route:

```
            <A href="/">Index</A>
            <A href="/about">About</A>
            <A href="/newroute">newroute</A>
```
solid starts to behave clunky:
you need to refresh the page in the browser in order to see the newest changes.

Creating a new route f.e. `newroute.tsx` in `routes` folder fails to register.
<img width="2527" alt="Screenshot 2023-01-02 at 21 55 00" src="https://user-images.githubusercontent.com/917231/210273925-ec1b9c77-24e9-4253-8330-0c5bd062aff9.png">

this doesn't happen when using `localhost`

after some tries accessing the site trough `192.168.1.1` seems to start working out of nowhere, however hmr doesn't work.

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
