### ISSUE TITLE
solid-start-cloudflare-workers hotreload not working

### ISSUE THREAD

**Issue by aminroosta** [solidjs/solid-start#618]
Thanks for putting together the cloudflare adapter.

The live/hot reload feature is broken.
Everything else works fine, including deploying to CF with wrangler.

<details><summary> Here is my config file for reference: </summary>

```ts
// vite.config.ts
import solid from "solid-start/vite";
import { defineConfig } from "vite";
import cloudflare from "solid-start-cloudflare-workers";

export default defineConfig({
  plugins: [solid({adapter: cloudflare()})],
});
```
</details>

**Comment by nksaraf** [comment]
Can you make a small repro of how it's broken with some description?

**Comment by AlexErrant** [comment]
FWIW live reloading currently works for me in [my proj](https://github.com/AlexErrant/Pentive/tree/main/hub). _Stateful_ hot reloading doesn't always work, but I think that's a [Solid thing](https://github.com/solidjs/solid-refresh#limitations).

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
