### ISSUE TITLE
[Docs] Deployment details

### ISSUE THREAD

**Issue by radubrehar** [solidjs/solid-start#630]
First of all, thanks for all the great work of everyone here!

I just gave solid-start a go, and tried to deploy to vercel.
After about 1h of dubbling around, I managed to do that - after i found the adapter

```js
import solid from "solid-start/vite";
import vercel from "solid-start-vercel";
import { defineConfig } from "vite";

export default defineConfig({
  plugins: [
    solid({
      adapter: vercel({ prerender: true }),
    }),
  ],
});
```
Obviously without the adapter, the vercel deployment failed.
Then, after finding some docs on adapters, I tried `vercel({ edge: true, prerender: true })` which also failed - seems like `edge: true` throws an error on vercel

<img width="1241" alt="Screenshot_2023-01-06_at_15 03 26" src="https://user-images.githubusercontent.com/196656/211022065-99541a14-1583-44fd-b59b-a4d24e961c37.png">

Then I removed the flag and it worked.

**My point - we need to put up some docs about deployment on the site at https://start.solidjs.com**
I expected to find something there but I didn't. At least some links to various resources.

If you find this useful and needed, I can send a PR

**Comment by ryansolid** [comment]
It looks like Node libraries are getting pulled in. Vercel edge doesn't support Node. Are you using any libraries that use node?

**Comment by radubrehar** [comment]
Hi @ryansolid!
The above error was mentioning `edge: true` just to illustrate the fact that we need docs about deployment - not only for `edge: true`

On the docs site I haven't found any details about how to deploy a solid start app - so I think it would be useful to have a section on that.

**Comment by stevemk42** [comment]
Hello.
First and foremost, thanks for all the great work of @ryansolid and his team, SolidJS is just my everyday thang as I progress and uncover how useful and practical it is.
I have the same request as @radubrehar . I cant get my solid-start template deployment on VERCEL to work (I get a 404). I even chose to deploy the blank one (typescript and with tailwind-css) to start from there, it didnt work. I think its probably a folder configuration issue (or something more advanced), and Im quite lost at searching how to fix this. Documentation would be greatly appreciated on that matter. Thanks in advance.
Its is probably a lighter issue than @radubrehar 's, but the request is the same (documentation about deployment to vercel), so I chose not to open another thread

**Comment by radubrehar** [comment]
@stevemk42 I managed to make it work - my issue was using the edge flag in the vercel adapter

**Comment by radubrehar** [comment]
@stevemk42 did you use the vercel adapter in your solid plugin in vite? - see the very first comment of the issue how you should use it

**Comment by stevemk42** [comment]
@radubrehar thanks for helping me.. Actually I had to change the .ts to .js, because of a type issue importing solid-start-vercel, then I added the option you mentionned. Unfortunately, I still get a 404, so I think its a configuration problem, not a build problem.. 
The build looks correct
```

16:27:40.922 | Retrieving list of deployment files...
-- | --
16:27:41.420 | Downloading 99 deployment files...
16:27:41.981 | Restored build cache
16:27:42.024 | Running "vercel build"
16:27:42.450 | Vercel CLI 28.13.0
16:27:42.756 | Build Completed in /vercel/output [116ms]
16:27:43.832 | Generated build outputs:
16:27:43.832 | - Static files: 101
16:27:43.832 | - Serverless Functions: 0
16:27:43.832 | - Edge Functions: 0
16:27:43.832 | Deployed outputs in 1s
16:27:44.291 | Build completed. Populating build cache...
16:27:44.319 | Uploading build cache [29.00 B]...
16:27:44.625 | Build cache uploaded: 306.05ms


```
my output directory structure looks like this: (I switched the option on for the time to screenshot it)
![Files within  – Brave](https://user-images.githubusercontent.com/62759300/214606014-c2aa3b7a-7c31-45b6-8151-61da9d9635d9.jpg)

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
