### ISSUE TITLE
[Docs] No client-side javascript?

### ISSUE THREAD

**Issue by NathanPip** [solidjs/solid-start#634]
Hello, I'm still fairly new to the solid (and loving it) so this may be a dumb question but is there any reason why client-side javascript would be disabled for the docs site? I tried implementing a simple dark mode with a toggle button since there was none but noticed the onClick event on the toggle button was not firing. So I tested some other things like a signal update on an interval and a Custom Event listener and nothing seemed to work.

Here is a replication of the issue with a dark mode toggle button and a counter button inside the header. https://github.com/NathanPip/solid-start/tree/docs-dark-mode

**Comment by ryansolid** [comment]
The docs site uses the new experimental partial hydration + hybrid routing solution that ships significantly less JavaScript. In this model most of the JavaScript isn't shipped to the browser except within designated locations. The DX of this experience is a bit lacking and non-obvious which is why it is still experimental but we wanted to dogfood it to get a good idea.

**Comment by NathanPip** [comment]
> The docs site uses the new experimental partial hydration + hybrid routing solution that ships significantly less JavaScript. In this model most of the JavaScript isn't shipped to the browser except within designated locations. The DX of this experience is a bit lacking and non-obvious which is why it is still experimental but we wanted to dogfood it to get a good idea.

Oh cool! Is this similar to how Astro's islands work?
