### ISSUE TITLE
Setting Content-Encoding: gzip results in Content Encoding Error

### ISSUE THREAD

**Issue by btakita** [solidjs/solid-start#675]
From what I gather, solid-start does not currently supports gzip or br component html payload compression so this would be a feature request. AWS Lambda has limits on the size of the payload, so this would be useful for serving large payload...and it would probably be a performance boost for serving html.

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
