### ISSUE TITLE
Using createRouteAction() without params

### ISSUE THREAD

**Issue by Handola** [solidjs/solid-start#678]
Hi,
createRouteAction() does not work correctly if no function parameters are used. The pending value is not updated:
```tsx
const [echoing, echo] = createRouteAction(async () => {
  await new Promise((r) => setTimeout(r, 1000));
  console.log("Hello!");
});

// ...

<button onClick={() => echo()} disabled={echoing.pending}>
  Echo
</button>
```

Something like this works:
```tsx
const [echoing, echo] = createRouteAction(async (foo: string) => {
  await new Promise((r) => setTimeout(r, 1000));
  console.log("Hello " + foo);
});

// ...

<button onClick={() => echo("Foo")} disabled={echoing.pending}>
  Echo
</button>
```

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
