### ISSUE TITLE
Example `with-prisma` type error on unused `sessionSecret`

### ISSUE THREAD

**Issue by meldron** [solidjs/solid-start#681]
Hi folks,

I just noticed that `with-prisma` contains a type error in `src/db/session.tsx`. 

```ts
const sessionSecret = import.meta.env.SESSION_SECRET;
```

> Property 'SESSION_SECRET' does not exist on type 'ImportMetaEnv'.

Furthermore the `sessionSecret` is not used in `createCookieSessionStorage`.

Thanks for all the hard work!
meldron

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
