### ISSUE TITLE
The page head `title` is written two times on revisits to the pages

### ISSUE THREAD

**Issue by Spiralis** [solidjs/solid-start#688]
The first page load is fine, but when navigating to a page for the second time, the title tag is written twice. The actual title along with an empty title tag. 

The first page that is loaded gets the extra blank title tag appended **after** its original title tag. The other pages that are navigated to using routing gets the extra blank title tag appended **before** the actual title. The route-navigated pages that has the blank title tag first loses the title in the browser.

This happens for me on `run dev` as well as for `run build` using both `solid-start-vercel` and `solid-start-static` adapters.

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
