### ISSUE TITLE
solid-start-aws: configurable clientAddress & method in entry.mjs

### ISSUE THREAD

**Issue by btakita** [solidjs/solid-start#696]
@thdxr brought to my attention that `sst` is the target for the `solid-start-aws` package.

https://github.com/solidjs/solid-start/issues/689#issuecomment-1407727363

I'm using the raw `aws-cdk-lib`, which apparently create a different shape to `event.requestContext`.

I can add what I observe as a conditional into `entry.mjs`, however it seems like `event.requestContext` is dependent on the cdk stack configuration. Since `event.requestContext` can potentially have any shape, the `solid-start-aws` default function can include an option to configure the path to `clientAddress` & `method`.

**Comment by thdxr** [comment]
in non edge mode it expects an API gateway v2 request if that helps

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
