### ISSUE TITLE
solid-start-aws: aws-cdk-lib stack: Cannot read properties of undefined (reading 'method')

### ISSUE THREAD

**Issue by btakita** [solidjs/solid-start#697]
In a raw `aws-cdk-lib` stack, `event.requestContext.http.method` & `event.requestContext.http` is not present.

The shape of `requestContext` I'm getting is:

```js
    requestContext: {
      resourceId: 'aabbcc,
      resourcePath: '/{proxy+}',
      httpMethod: 'GET',
      extendedRequestId: 'aabbbccdddee',
      requestTime: '30/Jan/2023:22:16:14 +0000',
      path: '/prod/favicon.ico',
      accountId: '123456',
      protocol: 'HTTP/1.1',
      stage: 'prod',
      domainPrefix: 'bbccdd,
      requestTimeEpoch: 1675116974063,
      requestId: '91573d85-4935-4254-9006-d3030e6b5fee',
      identity: [Object],
      domainName: 'v2vzpo1sng.execute-api.us-east-1.amazonaws.com',
      apiId: 'v2vzpo1sng'
    },
```

Making the `method` getter configurable may be a general solution:

https://github.com/solidjs/solid-start/issues/696

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
