### ISSUE TITLE
WebSocket never connects in `with-websocket` template

### ISSUE THREAD

**Issue by spiffytech** [solidjs/solid-start#705]
When I initialize a project using the `with-websocket` template, the WebSocket never connects. DevTools shows the network request stays in the `pending` state for 4.0 minutes until the request times out, and never sends/receives any messages.

After the timeout, the console will print an error that the connection failed, and the `setInterval` that sends messages will error out because the socket is `CLOSED`.

![image](https://user-images.githubusercontent.com/77867/216193826-dfe4e99b-067f-4f8b-8b29-2494d060f0f6.png)

## Reproduce

```sh
npm init solid  # Choose with-websocket
npm install solid-start-node  # Template is missing this dependency
npm run dev -- --open
```

Open DevTools and register an account.

**Comment by ryansolid** [comment]
@nksaraf Is this example Cloudflare only?

**Comment by nksaraf** [comment]
Yeah

**Comment by spiffytech** [comment]
Is Node.js WebSocket support documented elsewhere, or planned for implementation?

**Comment by nksaraf** [comment]
Its not implemented, I want to standardize the web-socket support across the platforms that can support it.

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
