### ISSUE TITLE
spa-test: Node 18 required to bump @playwright/test >= 1.26.0

### ISSUE THREAD

**Issue by birkskyum** [solidjs/solid-start#707]
Continuation of #704

When updating @playwright/test to 1.26.0 and beyond (same result all the way to latest 1.30.x), the "client side rendering" tests in spa-test will error. The rendered template is:

```tsx
<div id="content">
<h1>Root</h1>
<FileRoutes />
</div>
```

The `<FileRoutes />` cover two routes: index.tsx (path: "/") and about.tsx (path: "/about"). The content from these two routes is a simple page title (h2), and it is not included, breaking the test.

By manually adding said routes like below, the tests does pass, narrowing the issue down to incompatibility between **FileRoutes** and this new playwright version:

```tsx
import { Meta, FileRoutes, Scripts, Routes, Route } from "solid-start";
import { Suspense } from "solid-js";
import About from "./routes/about";
import Index from "./routes/index";

export default function Root() {
  return (
    <>
      <div id="content">
        <h1>Root</h1>
        <Routes>
          <Route path="/" component={Index} />
          <Route path="/about" component={About} />            
         </Routes>
      </div>
    </>
  );
}
```

**Comment by birkskyum** [comment]
FileRoutes returns in both 1.26.0 and 1.25.2 the following:

```ts
[{"path":"/about"},{"path":"/"}]
```

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
