### ISSUE TITLE
[solid-start-node] missing `rollup` peer dependency

### ISSUE THREAD

**Issue by rtritto** [solidjs/solid-start#713]
## Summary
`rollup` is a peer dependency of `@rollup/plugin-node-resolve` (dependency of _solid-start-node_).
It's a transitive peer dependency and it should be added in peerDependencies of _package.json_ of `solid-start-node`.

## Alternatives:
- copy the used/needed code of `@rollup/plugin-node-resolve` and remove it
- move `@rollup/plugin-node-resolve` to dev dependencies and add/use it during build

## Steps to reproduce
- `yarn init -y`
- `yarn set version canary`
- `yarn add @solidjs/meta @solidjs/router solid-js solid-start solid-start-node undici vite@3`
- output:
```console
➤ YN0000: ┌ Resolution step
➤ YN0060: │ solid-start-node@npm:0.2.19 [1528a] provides rollup (p92e50) with version 3.13.0, which doesn't satisfy what @rollup/plugin-node-resolve and some of its descendants request
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: Done with warnings
```

**Comment by philipbordallo** [comment]
This is due to [`@rollup/plugin-node-resolve` at `3.13.0` wanting a peer dependency `rollup` at `^2.42.0`](https://github.com/rollup/plugins/blob/node-resolve-v13.3.0/packages/node-resolve/package.json#L54-L56) and that `solid-start-node` uses `rollup` at `^3.10.0`, which doesn't fulfill that peer requirement.

At one point `@rollup/plugin-node-resolve` was updated to `^15.0.1` (615a5f0) which would have resolved this but it looks like @ryansolid reverted it (20de367).

Ideally whatever was causing the weirdness with `v15` of `@rollup/plugin-node-resolve` can be fixed but in the mean time if that warning message is bothersome, you should be able to temporarily disable it via [yarn `packageExtensions`](https://yarnpkg.com/configuration/yarnrc#packageExtensions) and setting the `peerDependenciesMeta` to be optional.

**Comment by rtritto** [comment]
Thanks for reply.
#753 should fix this.

**Comment by rtritto** [comment]
Fixed in [commmit](https://github.com/solidjs/solid-start/commit/bcbbcb1e3998afd6ffcbd2455c64924bf6e60787) after upgrading _@rollup/plugin-node-resolve_ to v15
