### ISSUE TITLE
config.adapter.build (npm run build) arguments do not match Adapter#build argument types

### ISSUE THREAD

**Issue by btakita** [solidjs/solid-start#719]
https://github.com/solidjs/solid-start/blob/main/packages/start/bin.cjs#L185

```ts
config.adapter.build(config, { ... })
```

https://github.com/solidjs/solid-start/blob/main/packages/start/vite/plugin.d.ts#L3

```ts
export type Adapter = {
  start(options: Options): Promise<void>;
  build(options: Options): Promise<void>;
  dev(options: Options): Promise<void>;
  name: string;
};
```

The arguments passed to `config.adapter.build` do not match the `Adapter` `build` function type arguments.

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
