### ISSUE TITLE
cant compile ".jsx" file on node environment

### ISSUE THREAD

**Issue by PuddingJoker** [solidjs/solid-start#734]
when i use solidjs and typescript to achieve ssr, the library “swiper” throw an error, it seems solid-start cant compile “jsx” file on node environment, here is error msg:
An error occured while server rendering /test:
	Unknown file extension ".jsx" for /Users/username/solidTest/node_modules/swiper/solid/swiper.jsx

**Comment by PuddingJoker** [comment]
please check the repository:  [](https://github.com/PuddingJoker/solid-swiper.git)

**Comment by PuddingJoker** [comment]
if i dont use ssr，it will work，but i need ssr.  

vite.config.js:

export default defineConfig({
  plugins: [solid(ssr:false)]
});

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
