### ISSUE TITLE
appRoot cannot be an absolute path

### ISSUE THREAD

**Issue by viridia** [solidjs/solid-start#736]
Line 128 in router.js, it's doing a "join", which blindly concatenates the two paths.

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
