### ISSUE TITLE
<Title> in root.tsx (<Head>) doesn't work if there is not other <Title> in the tree

### ISSUE THREAD

**Issue by DaniGuardiola** [solidjs/solid-start#738]
If there is no `<Title>` present in the subtree, the fallback `<Title>` inside `<Head>` in `root.tsx` doesn't work.

This only happens under specific conditions:

1. Load a page that **does** have its own `<Title>` defined.
2. Do a client navigation to a page that doesn't.

I've noticed that the `<title>` tag in the DOM is empty.

Here's a repro, see the `routes/index.tsx` where I've commented out the `<Title>` usage (https://github.com/DaniGuardiola/solid-start-title-repro/blob/main/src/routes/index.tsx#L7).

https://github.com/DaniGuardiola/solid-start-title-repro

Steps:

1. Load the `/about` page initially (it'll actually load the 404 page since that route is not defined).
2. Click "Index" at the top.

Versions:

```
@solidjs/meta 0.28.2
@solidjs/router 0.7.0
solid-js 1.6.10
solid-start 0.2.20
```

**Comment by DaniGuardiola** [comment]
I've just realized that some meta tags are doing weird stuff too. For example my `og:description` tag is being duplicated. I couldn't repro this on the linked repo though :/

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
