### ISSUE TITLE
ssr-manifest generated for solid-start-static

### ISSUE THREAD

**Issue by murphye** [solidjs/solid-start#741]
I am using `solid-start-static` as such to build a SSG:

```ts
export default defineConfig({
  plugins: [solid({
    solid: { hydratable: true },
    adapter: 'solid-start-static',
  })],
  build: {
    ssrManifest: false,
  }
});
```

However, `solid-start` seems to be hard-coding the `ssrManifest` resulting in `ssr-manifest.json` being generated when it's not needed.

Code Reference: [solid-start-static](https://github.com/solidjs/solid-start/blob/4e2ba7f02c65a969c1d47e829224048dfca5f49d/packages/start/bin.cjs#L195)

**Comment by atk** [comment]
Isn't it used internally to grab the list of items that need to be server-generated? Even so, it should be removed afterwards, if that is the case.

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
