### ISSUE TITLE
component level data fetching server-side

### ISSUE THREAD

**Issue by subhasishdas159** [solidjs/solid-start#750]
Hello I'm next js dev, trying to learn solid start. I can't find an example to do server-side component level data fetching.

Suppose I have a footer component, I want to fetch some data in the footer serverside. This will be automatically fetched in the server and passed to client wherever the footer component is added.

**Comment by boehs** [comment]
Have you read the docs? Look into `routeData` and `createServerData$`

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
