### ISSUE TITLE
Empty title el in root.tsx cases page to not render

### ISSUE THREAD

**Issue by rolanday** [solidjs/solid-start#761]
Empty title el in root.tsx cases page to not render

// root.tsx
```
    <Html lang="en">
      <Head>
        <Title></Title>
        <Meta charset="utf-8" />
        <Meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Body>
      ....
```

Repro steps.

- Create new project using tailwinds config option
- Clear Title inner el
- Reload page

<img width="970" alt="Screen Shot 2023-02-21 at 1 38 28 AM" src="https://user-images.githubusercontent.com/3402123/220307206-0c110a4d-50c2-483e-995e-59ae96d1e25b.png">

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
