### ISSUE TITLE
Incorrectly render component with SSR open

### ISSUE THREAD

**Issue by pakholeung37** [solidjs/solid-start#762]
![image](https://user-images.githubusercontent.com/16984253/220347890-25cc8637-b098-412b-a78b-f3d6568f79c5.png)
```tsx
// components/button.tsx
<button class={props.icon ? "flex" : ""}>
    <Show when={props.icon}>
      <span>{props.icon}</span>
    </Show>
    <Show when={props.children} keyed>
      <span>{props.children}</span>
    </Show>
  </button>
```
```tsx
// routes/index.tsx
<main>
    <Button icon={<span>icon</span>}>content</Button>
    <div>
      correct render:{" "}
      <button>
        <span>icon</span>
        <span>content</span>
      </button>
    </div>
  </main>
```
You can find the reproduction here: https://github.com/pakholeung37/solid-start-bug-report

**Comment by pakholeung37** [comment]
relate #281
I found it's because I read props.icon and props.children multiple time cause hydration error. It has to wrap in `children(() => props.icon)` to solve this case.

ps: I found `children` api very confusing. because it should use to solve JSXElement as props passing not just props.children.

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
