### ISSUE TITLE
Solid Start Docs update request  for server$.request

### ISSUE THREAD

**Issue by dskaiser82** [solidjs/solid-start#775]
Our team needed to get the request object via server$.
We originally tried useServer Context, but little did we know you can use server$.request.

Request to update the docs

**Comment by peerreynders** [comment]
Seems like `server$.request` is just syntax sugar for `this.request`. Server functions are [passed](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call#thisarg) a [`ServerFunctionEvent`](https://github.com/solidjs/solid-start/blob/2d197477a3c837e2fb7cc4fa05a1a86bde5e1552/packages/start/server/types.tsx#L66-L69) via [`this`](https://github.com/solidjs/solid-start/blob/2d197477a3c837e2fb7cc4fa05a1a86bde5e1552/packages/start/server/server-functions/server.ts#L199).

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
