### ISSUE TITLE
Solid-start depends on itself

### ISSUE THREAD

**Issue by joshdchang** [solidjs/solid-start#784]
I am getting a very strange error when trying to deploy a vanilla solid-start project to vercel (straight from the CLI, with no modifications). Works perfectly in dev.

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/17419116/222874114-14000e1a-97dd-487f-b0eb-03399a4f3ddc.png">

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
