### ISSUE TITLE
Hydration broken in SSR app when intializing a signal based on the isServer flag

### ISSUE THREAD

**Issue by klener89** [solidjs/solid-start#789]
### Describe the bug
I'm running in an unexpected behaviour when creating a Signal with a bare solid-start app with SSR.
The DOM node does not update, even though a console.log shows the correctly set value.
The real world use case for this would be to `access localStorage` on the client to extract stored values. 
When navigating to a different route and back the value is set correctly.

### Steps to Reproduce the Bug or Issue
1. create bare solid-start app with SSR and Typescript
2. create Signal and set initial value based on the isServer flag
3. print text to console and render it

```
const [text, setText] = createSignal<string>(isServer ? "server" : "client");
  console.log(text());
  createEffect(() => {
    console.log(text());
  });

  return (
    <div>
      <div>{text()}</div>
    </div>
  );
```

### Expected Behaviour
Both DOM and console showing the same value of text(). In this example it would be "client"

### Screenshot
<img width="601" alt="Screenshot 2023-03-06 at 17 29 34" src="https://user-images.githubusercontent.com/17904669/223171537-c33bd80e-643b-48cd-a29b-286e8af27e3f.png">

**Comment by ryansolid** [comment]
For Hydration to work server and client state have to match, so using isServer to initialize state will cause a mismatch. The best way to get around this is use a `createEffect` or `onMount` hook to set the state to the client state. This will trigger after hydration.

**Comment by klener89** [comment]
Thanks for the fast help @ryansolid .

Your suggestion works, but has the negative effect of `flashing elements`. Until `onMount` is fired, the "dumb" server state is shown. That results in flashing elements/text and is bad for the user experience.

I guess storing the values on the server is an option, but I was hoping for a cleaner solution in terms of data privacy. Working with localStorage is a lot more difficult like this.

On another note: is this documented somewhere? I was searching heavily for similar problems, but could not find any reference in the docs.

**Comment by ryansolid** [comment]
Probably not specifically. There is a gap at least in the current docs here, because the SSR docs on Solid site are pretty minimal (https://www.solidjs.com/guides/server) and SolidStart docs are little more than feature references at this point. Dealing with local storage is an interesting one. This property of client matching server for hydration is shared by all JavaScript frameworks so it's one of those things.

**Comment by klener89** [comment]
Is there any specific reason why every framework is doing it this way? Isn't the attribute `data-hk` used for hydration-key matching? I guess its cleaner if both states are matching for data integrity, but does that need to be a requirement?

I will work around it for now, thanks a lot for your help! You can close this issue if you feel there is no need to explore this topic further.

**Comment by ryansolid** [comment]
data-hk is Solid specific because JSX can be created out of order. But while maybe text is curable, a difference in state can lead to a different branch being taken, different things being rendered. I don't want to rely on this too because potential of resumability in the future. That is not doing any hydration. As we optimize for startup we do less work skip more paths on initialization.
