### ISSUE TITLE
createServerData$ is broken since solid-start version 0.2.19. It returns HTML instead of JSON.

### ISSUE THREAD

**Issue by acromarco** [solidjs/solid-start#790]
### Setup 
  * `pnpm create solid`
  * No SSR

### Code:

```typescript
import { Title, useRouteData } from "solid-start";
import { createServerData$ } from "solid-start/server";

export function routeData() {
  return createServerData$(async () => {
    return {
      testData: 'testData'
    };
  });
}

export default function Home() {
  const getRouteData = useRouteData<typeof routeData>();
  return (
    <main>
      <Title>Hello World</Title>
      RouteData: <div>{getRouteData()?.testData}</div>
    </main>
  );
}

```
### Unexpected result

The routeData URL returns HTML instead of JSON.
The problem happens in dev mode and also in the built version.

![image](https://user-images.githubusercontent.com/6649901/223287815-3b97035c-a493-4726-9d53-c4355c677916.png)

The console looks like:
![image](https://user-images.githubusercontent.com/6649901/223289906-5c68b7d9-2122-4f72-90b5-bca171dca03a.png)

### Affected versions

Reproducible with solid-start version 0.2.19 - 0.2.23.
Version 0.2.18 is the last version that works.

**Comment by notme1560** [comment]
Are you using `ssr: false`? I'm having the same problem, seems like it might have been introduced [here](https://github.com/solidjs/solid-start/commit/0a27fc2d977d19d7fce169eb6e8c6c39c6c33272) in 0.2.19. I'm not sure why `server$` methods can't work without SSR mode, but a better error message would be nice.

**Comment by acromarco** [comment]
Yes, I'm using `ssr: false`.

**Comment by lxsmnsyc** [comment]
Yes this is related to `ssr: false` disabling the server functions

**Comment by ryansolid** [comment]
Yeah I had to do this for consistency. Because if you wrote components that have client side only side effects it could crash the server when it imported them. People using ssr: false were not expecting client code to be present on the server so it made it errors that made no sense. Until we can do smarter code separation it meant I needed to disable server$ functions for ssr: false. 

I guess technically they aren't being disabled is the problem? And it is trying to fetch against a non-existent end point so its just responding with the catch all.

**Comment by lxsmnsyc** [comment]
@ryansolid What I think is, I'm not sure if this has been disproven, that `server$` function isn't registered in the server if the module it is located from is only loaded on the client?

**Comment by ryansolid** [comment]
Yes so technically if you put all your server functions in a file that you import from both the components that use it and from the root of the project it should work still.

**Comment by matulek** [comment]
Shouldn't there be at least some 404 error when the server function HTTP request is called from the client? There seem to be no indication that something is wrong when working on a project, it just doesn't work.

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
