### ISSUE TITLE
Does solid-start-cloudflare-workers adapter unable to pnpm dev?

### ISSUE THREAD

**Issue by dzolt** [solidjs/solid-start#791]
### Discussed in https://github.com/solidjs/solid-start/discussions/788

<div type='discussions-op-text'>

<sup>Originally posted by **dzolt** March  6, 2023</sup>
Hey! So I've installed solid-start-cloudflare-workers adapter to push my solid app to the cf workers and connect it to D1 db. 

I can run wrangler dev and it opens up almost fine (I have some issue with better-sqlite3 saying that it was compiled against differend node.js version and I also cannot resolve it) but it works.

However when I run command "pnpm dev" to start solid locally, miniflare throws an error seen in the screenshot below. Anyone has any idea why is that happening?
![image](https://user-images.githubusercontent.com/40149946/223128453-c0dc57ec-b878-4601-aa65-1a895cddd979.png)
</div>

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
