### ISSUE TITLE
Make logo in docs redirect to / when clicked

### ISSUE THREAD

**Issue by VIEWVIEWVIEW** [solidjs/solid-start#805]
I think it would make sense to make the logo clickable and redirecting to "/"

https://github.com/solidjs/solid-start/blob/29d5445134a639299312e64163a69fc826f953f4/docs.root.tsx#L91-L97

**Comment by ryansolid** [comment]
This is fixed in the new Solid Beta.

In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
