### ISSUE TITLE
create-solid todomvc project is broken when SSR is disabled

### ISSUE THREAD

**Issue by jarhodes314** [solidjs/solid-start#813]
Running `pnpm create solid` and supplying the following options causes the resulting template to be a broken project:

```
✔ Which template do you want to use? › todomvc
✔ Server Side Rendering? … no
✔ Use TypeScript? … yes
```

If I now run `pnpm i`, `pnpm dev --open`, I'm presented with a stack trace:

![image](https://user-images.githubusercontent.com/30299230/228035436-884c32b3-4457-4294-b700-e6d22d08f697.png)

After modifying `vite.config.ts` to enable SSR, the problem goes away as expected. I'm presuming the issue is with the use of `createServerData$` which appears to be incompatible when running solid start with only CSR. With this, I consider there to be three potential bugs here:

1. `create-solid` allowed me to create a broken project
2. The error message indicating that I can't use server data on a non SSR project is not at all clear
3. If this is a deliberate design decision, I cannot find any documentation which explains this limitation

**Comment by ryansolid** [comment]
Yeah this example makes extensive use of server actions which requires ssr in their current form. We need to guide the CLI better here. It's tricky because certain examples use certain features. The Todo example and auth I think require ssr: true. Another one only works on Cloudflare. We need to separate perhaps between templates and examples that showcase features.

**Comment by RonenEizen** [comment]
@ryansolid Does this mean that all server side functions such as createServerAction$, createServerData$ and other are limited to SSR mode only?

**Comment by joshuafcole** [comment]
Seconding @RonenEizen's request to add this to the documentation. Is changing this to enable CSR apps to benefit from the implicit API magic on the docket? For highly dynamic use cases, the initial render time benefits of SSR are heavily outweighed by the cost of trying to keep duplicated state synchronized across client and server, but the implicit API magic of `createServerData$` and friends would be still be very helpful.

**Comment by ryansolid** [comment]
Yeah it is intended to solve this. We need a different way to pull them out. Currently, it transforms and then it collects at runtime(at import) which the CSR version never hits. Initially, we supported it until people were confused that they were getting server errors on their client libraries running side effects on the server. Basically imports of client libraries on the server, even if they never ran the exported methods (or even included them) might end up with references to `window` or `document` top level and those would crash the server. So we stopped bringing these in on the server but it prevents this mechanism from working.

**Comment by joshuafcole** [comment]
Ah, that makes perfect sense in retrospect. I actually ran into the opposite problem (server code getting pulled down to the client) on my first pass at solving this with a POST handler in the route file since auth.js pulls in node-only packages (reasonably!) for it's server side session management. 

Given the ship has sailed on getting metadata into packages, is there any path you can see to this working in the future? I could potentially imagine some compile time magic wherein we tree-shake out imports that aren't used within the server-targeting callbacks, but that'd also elide anything you were intentionally pulling in for server-side side effects, not to mention add even more caveats about what you could expect the scope to look like within those callbacks. :/

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
