### ISSUE TITLE
[Question] SolidStart Cloudflare pages wrangler.toml 

### ISSUE THREAD

**Issue by a2xchip** [solidjs/solid-start#838]
How do I use env vars and bindings defined directly in `wrangler.toml` when using SolidStart + `solid-start-cloudflare-pages` full-stack app?

**Comment by AlexErrant** [comment]
Solid Start dev mode uses [the miniflare api](https://github.com/solidjs/solid-start/blob/f6b1e036d26ab991773c0d8918fbcb0612c0bf77/packages/start-cloudflare-workers/index.js#L18), which is documented [here](https://miniflare.dev/get-started/api).

Relevant paragraph:

> Unlike the CLI, the API won't automatically load configuration from .env, package.json and wrangler.toml files in the current working directory. You can enable this by setting the envPath, packagePath and wranglerConfigPath options to true

As an aside, I use .env files [in my own project](https://github.com/AlexErrant/Pentive/blob/main/hub/vite.config.ts#L14), so I can't speak from experience as to whether that paragraph works or not.

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
