### ISSUE TITLE
Using an HTTPS reverse proxy during development causes issues with solid-auth

### ISSUE THREAD

**Issue by ledburyb** [solidjs/solid-start#847]
I noticed on switching to a Caddy reverse proxy locally that my social login buttons were broken.

After investigation it appears that forcing http here causes some of the auth code to incorrectly build URLs with http instead of https:
https://github.com/solidjs/solid-start/blob/main/packages/start/node/fetch.js#L143

It looks like there's an open PR that touches this part of the code already and may fix this issue as well:
https://github.com/solidjs/solid-start/pull/821

**Comment by ledburyb** [comment]
If anyone else encounters this you can actually workaround it for now by adding an Origin header to your proxy, e.g.:

```
handle @app {
    reverse_proxy {
        to 127.0.0.1:3000
	header_up Origin "https://app.myproject.dev"
    }
}
```

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
