### ISSUE TITLE
Middleware doesn't work when using Client Side Routing

### ISSUE THREAD

**Issue by atmelmicro** [solidjs/solid-start#855]
Hello everyone,
when using the middleware example from the docs, no events are sent to the server if I use the `<A>` tag. If I switch to an `<a>` tag, or if I refresh the page it works just fine. 

https://user-images.githubusercontent.com/114749286/234531644-c0222db9-71aa-47bf-ac8a-6b8aa78d926d.mov

Thanks.

**Comment by atmelmicro** [comment]
Here is a repo with the issue https://github.com/atmelmicro/solid-middleware. Everytime the middleware is called, "In middleware" will be logged out. When navigating via the navbar (client side routing), no middleware calls are made, only when refreshing the page or using normal <a> tags.

**Comment by AnujSsStw** [comment]
yes same happened with me when i was looking a hackernews example

**Comment by ryansolid** [comment]
The repo is long gone it looks like. There might be confusion about when middleware is called. Ie.. client side routing can only call middleware when you are making API requests when loading the page. In any case:

In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
