### ISSUE TITLE
Dynamic components do not render in PROD mode

### ISSUE THREAD

**Issue by dskaiser82** [solidjs/solid-start#866]
Our team uses Dynamic components, which worked as expected in DEV mode.

However, Dynamic components do not render correctly on PROD mode.
https://www.solidjs.com/docs/latest/api#dynamic

Note:
Even using a Solid JS For did not fix this Prod issue

Example
```
{headerLinks?.map((link) => {
            return (
              <div class={styles.item}>
                <Dynamic component={link as ValidComponent} />
              </div>
            );
          })}
```

**Comment by ExorTek** [comment]
You should provide more details in my opinion, you can start by elaborating your code.

**Comment by LiamMartens** [comment]
@dskaiser82 what is the `link` object in this case? Is it a valid JSX component? Since you  are casting to a `ValidComponent` type you might not be passing a valid component

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
