### ISSUE TITLE
Add response headers in `server$` function without downgrading to raw `Response`

### ISSUE THREAD

**Issue by cpud36** [solidjs/solid-start#867]
I want to set response headers of `server$` function while using a plain js value responses.

Is this within project plans?

I imagine this could look like:
```typescript
const handler = server$(async () => {
  let init = {
    status: 201,
    headers: { 'Set-Cookie': 'foo=bar', 'ETag': '...' }
  ];
  return json({ name: 'hello' }, init);

  // or
  server$.responseHeaders.append('Set-Cookie', 'foo=bar');
  server$.responseStatus = 201;
  return { name: 'hello' };
});

// ...
let result = await handler();
console.log(result.name) // => 'Hello'
console.log(document.cookie) // => 'foo=bar'
```

**Comment by samualtnorman** [comment]
running into this
I would rather that instead of creating something new, we just use `useRequest()` which already exists for this purpose
I'd rather an API that looked like
```js
const handler = server$(async () => {
	const event = useRequest()
	const result = await somethingAsync()

	event.responseHeaders.set("set-cookie", `foo=${result.bar}`)

	return result.baz
})
```

https://github.com/solidjs/solid-start/blob/043577a6400b8461baa2345e70b665f86da9692f/packages/start/server/server-functions/server.ts#L160 currently constructs a `new Response` with hardcoded headers, it would be nice if this was configurable

**Comment by cpud36** [comment]
Would be nice too. But I assume it has implementation troubles.

AFAIK, useRequest does not work well with async functions. It will need AsyncTLS/CLS for that to work.

Not sure what is the project position on CLS.

**Comment by samualtnorman** [comment]
what's CLS?

**Comment by cpud36** [comment]
Continuation Local Storage.

It is a reincarnation of TLS(Thread Local Storage), but for asynchronous programming model

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
