### ISSUE TITLE
Node emits warning: "Status message is not supported by HTTP/2"

### ISSUE THREAD

**Issue by shareable-vision** [solidjs/solid-start#871]
`handleNodeResponse(webRes, res)` in `/solid-start/node/fetch.js` causes Node to emit warning:
"(node:103232) UnsupportedWarning: Status message is not supported by HTTP/2 (RFC7540 8.1.2.4)",
which may be avoided by setting `res.statusMessage`, only if `webRes.statusText` is not an empty string:

```
if (webRes.statusText) res.statusMessage = webRes.statusText;
```

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
