### ISSUE TITLE
„A“  element always renders whole page

### ISSUE THREAD

**Issue by ralfscheffler** [solidjs/solid-start#879]
Other then „Link“ in solidjs from solid-app-router ,„A“ in solid start renders  the whole Navigation page

**Comment by untlsn** [comment]
When you said "renders" you mean reload page or something else?

**Comment by ralfscheffler** [comment]
I put it on top of ROUTES in the root.tsx

**Comment by LiamMartens** [comment]
@ralfscheffler  you should use the components from solid; not just a normal `<a />`. They don't receive the logic for client side routing

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
