### ISSUE TITLE
Cannot redirect by Navigate component from clicking A tag in the same page

### ISSUE THREAD

**Issue by azmy60** [solidjs/solid-start#890]
Hello solid-start team! This is my first time submitting an issue here. I would also be interested to contribute to the project! So I think I've found a bug related to redirecting. This occurred when I tried to add `<A href="/">` to the [docs.root.tsx](https://github.com/solidjs/solid-start/blob/f79082078e21035dc6528c4cb4d31e02e4e9e9eb/docs.root.tsx).

Steps to reproduce:
- Add `<A href="/">` tag to the logo in [docs.root.tsx](https://github.com/solidjs/solid-start/blob/f79082078e21035dc6528c4cb4d31e02e4e9e9eb/docs.root.tsx)
- Open `/getting-started/what-is-solidstart`, and click the logo.
- The url changes to `/`, and every links become unresponsive.

Since [docs/index.tsx](https://github.com/solidjs/solid-start/blob/f79082078e21035dc6528c4cb4d31e02e4e9e9eb/docs/index.tsx) returns a `<Navigate href="/getting-started/what-is-solidstart" />`, It probably should stay in the same page, instead of going to `/`. (This works as expected in nextjs)

Note: It works fine if I link the A tag to `/getting-started/what-is-solidstart`

**Comment by ryansolid** [comment]
Yeah this was a bug with the Experimental Islands Router we were using and won't be present in the next update.

In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
