### ISSUE TITLE
Files in public folder in build (Node Adapter)

### ISSUE THREAD

**Issue by modmanx** [solidjs/solid-start#90]
Hello, we deployed new application using solid-start and after doing npm run build, we cannot open files in /public folder. It always gives us fallback route index.js. What could be the cause? We checked other examples (like hackernews-ts) and did not find any difference.

**Comment by ZeAmanuel28** [comment]
Can you mention to which Hosting Provider you are trying to deploy because Solid Start has adapters that can change the output of your code. Did you try to install these adapters? If not try to see these:
https://github.com/solidjs/solid-start/tree/main/packages
https://m.youtube.com/watch?v=O2kFXlNSdn0

If your node.js version is lower than node 14, try to install the latest or the LTS version.

**Comment by modmanx** [comment]
Hello, we are currently doing Dockerfile build on Cloud Run. We have same problem locally if we do `npm run build` and `cd` to dist and run `node index.js`

We are using solid-start-node.

**Comment by modmanx** [comment]
Hello again, we managed to fix the issue by moving files in public/ to public/assets, as assets seems to be hard-coded in connection with polka (i have not yet figured out why polka is used)

```
const server = polka().use("/assets",
		comp,
		assets_handler
	).use(comp, render);
```

**Comment by ryansolid** [comment]
Yeah when I first made the adapters I missed making them configurable. More of that stuff has come in over time. I just grabbed Polka because Luke Edwards makes good stuff and I figured since this was abstracted away the need for Express wasn't necessary. But maybe there are reasons to go with Express anyway given it is more known and used.

**Comment by modmanx** [comment]
I understand ;) I was just not sure if I missed something because https://github.com/solidjs/solid-start/tree/main/examples/hackernews-ts does not have public files in assets folder and it works just fine here - https://hackernews.ryansolid.workers.dev/

**Comment by ryansolid** [comment]
This should be fixed in alpha.69
