### ISSUE TITLE
solid-start-vercel adapter ignores build.rollupOptions.output.format: "es" in vite.config.ts

### ISSUE THREAD

**Issue by cs-clarence** [solidjs/solid-start#900]
I have this vite.config.ts file:
```ts
import solid from "solid-start/vite";
import vercelAdapter from "solid-start-vercel";
import { defineConfig } from "vite";
import baseConfig from "./vite.base.config";

export default defineConfig(() => {
  return {
    ...baseConfig,
    plugins: [
      solid({
        adapter: vercelAdapter({}),
      }),
    ],
    build: {
      rollupOptions: {
        output: {
          format: "es",
        },
      },
    },
  };
});
```

When I build with this config, I get the error:
```
Error [RollupError]: Module format "cjs" does not support top-level await. 
Use the "es" or "system" output formats rather.
```

It outputs 'cjs' even when I set the config to output es modules. This doesn't happen when using default adapter.

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
