### ISSUE TITLE
[Bug?]: Why must an absolute path be used to create routing data

### ISSUE THREAD

**Issue by mydracula** [solidjs/solid-start#945]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

![image](https://github.com/solidjs/solid-start/assets/71320199/edf2e39a-94da-4b76-a199-558b94fb686d)

```
export function routeData({ params, location }: RouteDataArgs) {
    return createServerData$(
        async ([slug, page]) => {
            const response = await fetch(`/api/searchList`, {
                method: "POST",
                body: JSON.stringify({
                    keyword: slug,
                    page: page
                })
            });
            return (await response.json());
        },
        { key: () => [params.slug, location.query['page'] || "1"] }
    );
}

```

### Expected behavior 🤔

![image](https://github.com/solidjs/solid-start/assets/71320199/b6b803b8-a8f6-40fb-9841-cab5948b6051)

```
export function routeData({ params, location }: RouteDataArgs) {
    return createServerData$(
        async ([slug, page]) => {
            const response = await fetch(`http://localhost:3000/api/searchList`, {
                method: "POST",
                body: JSON.stringify({
                    keyword: slug,
                    page: page
                })
            });
            return (await response.json());
        },
        { key: () => [params.slug, location.query['page'] || "1"] }
    );
}

```

### Steps to reproduce 🕹

<a href="https://discord.com/channels/722131463138705510/1132235767264059402">I also filed a ticket on discord and I can't resolve this issue</a>

Steps:

1. Create an API
2. Create routing data
3. Use internal API
4. Use routing data

### Context 🔦

An error is reported, the data cannot be obtained unless the full url is written

Isn't this called according to the current environment url?

### Your environment 🌎

```shell
win10
```

**Comment by syahzuan** [comment]
Following. Having the same issue for using relative URL for API route.

**Comment by atk** [comment]
Since we can start from any given path, we have no indication where the base path will end and the route path will start with only a relative path.

**Comment by mydracula** [comment]
> 由于我们可以从任何给定路径开始，因此我们没有指示基本路径将在哪里结束，并且路由路径将仅以相对路径开始。

I use the local development localhost:3000/api/path when I deploy the line may be a domain name xxx.com may be xxx.vercel.app, then I want to use the production environment also need to be manually modified? This is very inconvenient and very troublesome, if it is a relative path, then the current environment baseurl + relative path to form a complete API request address, this is not okay?

**Comment by atk** [comment]
What is the base URL then in that case? The hostname? Full path? Something in between?

The best way to manage different base paths right now is to use the --base argument in the vite build.

**Comment by mydracula** [comment]
> What is the base URL then in that case? The hostname? Full path? Something in between?
> 
> The best way to manage different base paths right now is to use the --base argument in the vite build.

Off topic, even if the --base parameter is configured, it cannot be solved routeData must use a complete url path, must define its host port, etc. The API route I defined cannot be called, that is, the relative path

![image](https://github.com/solidjs/solid-start/assets/71320199/1a21def6-9907-4ade-93b4-80d78992c70f)

**Comment by edivados** [comment]
@mydracula You are comparing how fetch works in the browser and on the server (node). On the client the browser knows on what website you are and will set the host accordingly when doing `fetch('/api/stundents')`. On the server this is not done since there is nowhere to take that information from.

You have to do that yourself. For example: `fetch(new URL("/api/stundents", baseURL))` 
Where you get the baseURL from is up to you.

- Hardcoding
- [Global constant replacement](https://v2.vitejs.dev/config/#define) at build time with vite
- Env variable at run time (process.env)

(There are probably other ways that I don't know of)

For example on Vercel you can get the domain of your deployment with `VERCEL_URL` or provide your own.
Something like this: `fetch(new URL('/api/stundents', "https://" + process.env.VERCEL_URL))`

<hr>

Now... doing a fetch against your own api routes inside [`createServerData$`](https://start.solidjs.com/api/createServerData) seems unecessary. [`createServerData$`](https://start.solidjs.com/api/createServerData) gets only executed on the server in the following two ways:

- SSR (Server): By calling the function (no HTTP request involved)
- Client (Browser): By a POST request against a generated route `/_m/<fnhash>` for that function

You are on the server inside createServerData$ and can  do the same thing you would do in an API route. Like database queries or reading from the file system etc..

You end up doing this:

```
Client: HTTP Request ===> Server (CreateServerData$):  HTTP Request ===> Server (API Route): Db query
```

While you could do this instead:

```
Client: HTTP Request ===> Server (CreateServerData$): Db query
```

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
