### ISSUE TITLE
Support router integrations of solid-app-router

### ISSUE THREAD

**Issue by arksun-bc** [solidjs/solid-start#96]
example usage: `src/entry-client.tsx`

```tsx
import { render } from "solid-js/web";
import { hashIntegration } from "solid-app-router";
import { StartClient } from "solid-start/entry-client";

render(() => <StartClient routerIntergration={hashIntegration}  />, document.body);
```

example change: `packages/start/entry-client/StartClient.tsx`
```tsx
import { MetaProvider } from "solid-meta";
import { Router } from "solid-app-router";
import { StartProvider } from "../entry-server/StartContext";
import Root from "~/root";

const rootData = Object.values(import.meta.globEager("/src/root.data.(js|ts)"))[0];
const dataFn = rootData ? rootData.default : undefined;

// typeof routerIntergration = RouterIntegration | undefined
// TODO: validate routerIntergration

export default ({ routerIntergration }) => {
  return (
    <StartProvider>
      <MetaProvider>
        <Router source={routerIntergration && routerIntergration()} data={dataFn}>
          <Root />
        </Router>
      </MetaProvider>
    </StartProvider>
  );
};

```
I hardcoded `hashIntegration` from the above solution, the outcome looks good to me

**Comment by ryansolid** [comment]
I've been thinking about exposing this more. The challenge in Solid is that component depth affects hydration so I sort of didn't want to expose the context tree. I'm thinking though this might be better to just do. But yeah now that we support client only mode I think having the ability to do hash routing makes sense.

**Comment by nksaraf** [comment]
@rturnq Could you review this once and see if its okay to do, and if there is anything we should consider specially? Otherwise I'll implement it as suggested

**Comment by zackpi** [comment]
Is this still under consideration? Or is there another way to use "hashIntegration" with solid-start

**Comment by devinrhode2** [comment]
I also have a need to do hash routing

dug through the code and concluded the easiest change is to add a prop to StartClient

However I think the more intuitive approach is to let users to see this in their generated root.tsx:
```tsx
<Router>
  <Routes>
     <FileRoutes />
```

I'm creating a "micro-app"/micro-frontend with solid at the core.

Given I'll be loaded into another app as a widget, inside a kind of pseudo iframe, I don't want to modify the main url path.

Separately, I'd like to create a "query router", instead of a hash router

**Comment by devinrhode2** [comment]
I don't mind passing something into StartClient, because reading and writing the apps state to the browsers url is a very global thing by nature....

...but... If we are passing something into StartClient we'll need to pass something into StartServer. With that, arises questions about client vs server routing semantics... I think ultimately people will just keep creating issues asking how to customize router props.

I think it's good to maintain the simple path spec for routing, although the underlying implementation of reading/writing to browser url needs to be customizable.

Glancing at the code for a few seconds, it seemed reasonable to shift `<Router>` into root.tsx

**Comment by devinrhode2** [comment]
If we don't shift to root.tsx, we'll need to add docs, and that is a loss imo.

**Comment by devinrhode2** [comment]
Actually, while I think code that necessitates more docs is less good than code that doesn't necessitate more docs, in this case I view it as necessary because I'm coming from 5 years with react, where all those apps had a `<Router>` component around the root of the application.

**Comment by devinrhode2** [comment]
Even if there was a `<Router>` in my generated root.tsx, I would still have searched Google for "solid.js hash routing".

I don't know what the performance cost is, but the cost in dx is very tiny imo

**Comment by devinrhode2** [comment]
> I've been thinking about exposing this more. The challenge in Solid is that component depth affects hydration so I sort of didn't want to expose the context tree. I'm thinking though this might be better to just do. But yeah now that we support client only mode I think having the ability to do hash routing makes sense.

Although hash routing would work for my use case, I'd definitely prefer a kind of querystring/searchparams based routing mechanism. I think it only really makes sense when embedding solid into larger apps.

**Comment by devinrhode2** [comment]
Alright

So I got this crazy "micro-app" thing mostly working

I think once scripts start hydrating the app, Solid router see's that the current route is not what the server originally rendered for. it's converting to a 404 because the consuming host doesn't have the url I `fetch()`d.

I guess what I really need this minute is a "memory" router... maybe need to use sessionStorage. For now I could read/write to a hard-coded key in sessionStorage, in future, I'd have to pass that to hydration code.

REGARDLESS of the underlying routing mechanism, I'll need to do patch-package or something... 

Any ideas on how to go about patching this in?

I guess easiest thing to do is fork the package, hard-code in the alternate `<Router source` and then leave it there - I could probably easily add in some api, but just not sure what kind of api we should be adding.

**Comment by devinrhode2** [comment]
I think a prop passed to <StartClient and <StartServer should be pretty easy, but then we have the duplication.

And ryan said this will have an effect on hydration... I don't even know if hard-coding in a different router source will even work...

**Comment by devinrhode2** [comment]
Sorry for the huge quantities of unrefined gibberish. I've edited it down a little bit.

**Comment by devinrhode2** [comment]
@nksaraf @ryansolid @zackpi @timbasel @arksun-bc @rturnq - I have opened a PR here: https://github.com/solidjs/solid-start/pull/1026
