### ISSUE TITLE
[Bug?]: Double rendering

### ISSUE THREAD

**Issue by MariuzM** [solidjs/solid-start#977]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I have raised this issue here https://github.com/swordev/suid/issues/251 but unsure if this is up to them or some issue with how SolidStart is rendering

### Expected behavior 🤔

Should not render text twice

**Comment by MariuzM** [comment]
Wrapping its inside elements into {``} solved 

```
    <Button variant="contained" onClick={() => setCount(count() + 1)}>
      {`Clicks1111: ${count()}`}
    </Button>
```

Is this a bug?

**Comment by ryansolid** [comment]
It sounds like a hydration bug. Would love a quick reproduction so I can look at it.

**Comment by MariuzM** [comment]
@ryansolid thank you, https://github.com/MariuzM/test_solid

**Comment by edivados** [comment]
Remove the `$` from the first button.
```jsx
  return (
    <main>
      <Button variant="contained" onClick={() => setCount(count() + 1)}>
        Clicks1111: ${count()}
      </Button>

      <Button variant="contained" onClick={() => setCount(count() + 1)}>
        {`Clicks1111: ${count()}`}
      </Button>
    </main>
  );
}
```

**Comment by BierDav** [comment]
Jup can confirm, same issue in my project when mixing string and signal values together

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
