### ISSUE TITLE
[Bug?]: 'this' keyword is equivalent to 'undefined'

### ISSUE THREAD

**Issue by MariuzM** [solidjs/solid-start#978]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Getting this message when doing build. 
```
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
```

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

**Comment by stickyburn** [comment]
Facing the same issue.

My app isn't using SSR, and implements Supabase on the client side. `@supabase/supabase-js` is the only installed dependency and this happens during build time(`pnpm run build`). Any help would be :100:

**Comment by ryansolid** [comment]
In setting up for SolidStart's next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
